#+title: Accelerate Professional Skill Development
#+author: SOV710
#+date: <2026-01-23 Fri>

* 目的

四个目的

在保证训练效果的同时加快训练过程的方法 (快速训练) 。

加速将战场经验教训转化并融入训练环境的方法——例如, 如果叛乱分子的战术不断演变, 就应该有办法将这种「元信息/策略变化」迅速整合进现有的培训项目中。 (快速知识共享) 。

能更快地将人员训练至更高的熟练度 (proficiency) 的方法 (加速熟练度提升)

确保训练效果稳定且持久的方法 (促进知识保留)

「熟练度 (proficiency) 」与「专业技能 (expertise) 」之所以存在区别, 是因为作者们确定是否有可能加速达到真正的「高水平熟练」 (有时也称为「精通」或「大师级水平」) 。

作者们表示, 或许整体上的精通仍然需要在领域内花费 10 年时间, 对此我们无能为力。

但我们确实知道的是: 现有的那些成功的加速培训项目, 能够加速的是熟练度的提升, 而非精通水平的达成。

而或许, 这就足够了！

* 传统的技能养成有什么问题?

我们大多数人大概会先问: 这个领域的技能树是怎样的？对此, 研究人员说: 不, 打住, 把那套都忘了吧。

首先, 这种训练方法实在太 TM 耗时了。毕竟, 这是主流的教学方法, 而研究人员正是被要求来改进这种范式的。一个更有趣的问题是, 为什么它会如此耗时。

对此有两个答案。其一, 人类通过构建关于某个领域的心智模型来学习。起初, 这些心智模型很粗糙, 无法指导有效的行动。因此, 新手会通过不断地构建、抛弃和重构心智模型来响应反馈, 从而快速地发展这些模型。然而, 到了某个阶段, 这些心智模型变得足够有效、足够复杂, 以至于它们成了「知识护盾」——即那些存在细微错误的心智模型, 它们​*之所以阻碍学生达到更高的专业水平, 恰恰是因为它们让学生能够拒绝异常数据*

将一个技能领域分解为原子化的技能是有风险的——由于技能层级本身的不完整性, 你很可能会无意中促使学习者构建出存在细微错误的心智模型。这继而会减缓专业技能的发展, 因为培训师此时必须做额外的工作——例如, 你必须将「摧毁知识护盾」作为一项教学目标来设计你的训练任务。最好能完全避免这种情况

层级化训练方法糟糕的第二个原因是, 对原子化技能的评估无法转化为对现实世界表现的评估。我想我们凭直觉就能明白这一点。针对基础技能的测试往往无法捕捉到在现实环境中应用技能时的细微差别。你可能在公司金融考试中表现优异, 却把一家公司经营得一塌糊涂, 因为你不知道在你所处的特定业务中应该留意哪些线索

这种训练方法糟糕的第三个原因是, 原子化的训练往往缺乏对实际应用场景的高度​*认知保真度*​。以著名的课堂学习理论「认知负荷理论」为例。该理论基本观点是: 「内在认知负荷」与学习任务本身的复杂性相关；「外在认知负荷」则是由学习过程中那些不必要且干扰图式获取的活动引起的。教师的职责是设计教学方法以减少外在认知负荷。作者指出, 当你的学生只需要应付考试时, 这套理论没什么问题, 但如果你的工作环境是在炮火连天中规划部队行动, 那么你的训练项目或许也应该包含一些「外在认知负荷」吧？

这种训练方法糟糕的第四个原因是, 当技能领域发生变化时, 更新培训项目变得异常困难。这一点在商业和军事环境中都至关重要——设想一下, 如果 (商业中的) 市场环境变化, 或者叛乱分子改进了他们的简易爆炸装置 (IED) 战术, 你就需要快速更新你的培训项目。但是层级化的教学大纲本身就难以更新。应该更新哪一课？哪个复杂程度？哪些先决条件需要改变？

这种训练方法糟糕的第五个原因是, 外部评估常常​*削弱学习者在实地的感知构建 (sensemaking) 能力*​。换句话说, 极其清晰的反馈有时反而会阻碍学生有效地从经验中学习, 这可能会减缓他们在进入真实世界领域后的学习速度

我们应该​*走捷径*

* 如何加速专业技能养成？

CTA, cognitive task analysis, 认知任务分析

CTA 最简单的两种形式: NDM 和 ACTA

CTA 能让你做到的, 就是​*提取*​出专家头脑中实际拥有的专业心智模型。这让你能够绕开设计完善的层级化技能树这一难题。

本书推荐的加速专业技能培训项目的通用结构如下:
1. 识别领域专家
2. 对已识别的专家进行认知任务分析 (CTA) , 提取其专业技能
   根据所使用的具体 CTA 方法, 这一步最初可能需要几个月时间, 并且需要对多位专家 (有时也包括一些新手) 进行多次访谈, 才能有效地完成提取工作。
3. 在进行第二步的同时, 你将建立一个包含疑难案例的案例库
    存储这些案例, 并根据难度指标对其进行分类编码。你可以请专家协助进行分类编码工作。
4. 接下来, 将你的案例库转化为一系列训练模拟情境
   这一步有点像一门艺术 —— 研究人员表示 「目前尚无一套通用的原则来指导如何设计出好的模拟情境」。 他们知道与现实世界保持认知保真度是关键——但这种保真度需要达到多高呢？这方面的训练项目形式多样, 从 (使用 VR 头显的) 完全虚拟模拟, 到海军陆战队采用的纸笔决策练习 (称为「战术决策游戏」) 不一而足。
5. 有些训练项目设计要求学习者自行进行感知构建 (sensemaking) ——即内省和反思他们从每次模拟中学到了什么。另一些项目则包含来自更有经验的从业者或在第一步中被识别为「专家」的人员的反馈。
6. 有些训练项目可能会预先呈现抽象或普适性的原则, 然后在训练模拟中对这些原则加以强调。
   例如, 海军陆战队有一条关于战场计划被打乱时的经验法则: 「持续移动, 抢占高地, 保持联络。」这是明确教授的。
7. 最后, 测试项目: 让学习者完成你设计的一系列从易到难的训练模拟。
8. 模拟训练中的反馈有时是定性的、多因素的。
   如 Gary Klein 的「影子盒」 (Shadowbox) 方法, 会在呈现的场景到达关键决策点时提出多项选择题 (例如, 「在心脏骤停的这个时刻 (定格视频), 你认为哪些线索是重要的？」) 。学习者随后将自己的答案与专家的答案进行比较, 并反思自己遗漏了什么。
   其他形式的反馈则不那么明确。美国海军陆战队的「战术决策游戏」是在群体环境中以纸笔形式进行的, 由一两位经验更丰富的指挥官引导。反馈是有机的, 自然产生于小组讨论中。Lia DiBello 的「战略演练」是在企业内部以小组形式进行的, 在模拟失败后, 仅给参与者提供三个问题进行讨论: (1) 哪里出了问题？(2) 这次我们将采取哪些不同的做法？(3) 我们如何知道新做法正在奏效？有时, 这还会结合一个由培训师引导的建设性练习。

几个显著特点

1. 注意案例库和模拟情境易于更新的特点
2. 技能保持与这种方法高度兼容——经验丰富的从业者可以参与一个间隔重复训练计划, 定期进行模拟训练。
   或者, 如果从业者无法进行模拟训练 (例如, 因为他们被派往离训练设施过远的地方) , 一种替代方案是在其调岗前进行「过度训练」——即密集的模拟训练, 这能带来较为平缓的技能衰退速度
3. 完全不做基础技能训练似乎有些极端——但作者指出, 训练模拟并不排斥基础技能的教学
4. 对于这种训练方法, 一个常见的反应是: 「等等, 如果新手没有任何基础概念训练, 就被直接扔到真实世界的任务中, 他们不会感到迷茫和不知所措吗？」
   这种「不知所措」的感觉或许最好被视为一种「合意困难」, 并且可能是为了达成加速目标而付出的可接受代价。


有两种核心学习理论是其训练方法的基础, 并且这两种理论可以结合运用:
- 认知灵活性理论 (Cognitive Flexibility Theory, CFT)
- 认知转型理论 (Cognitive Transformation Theory, CTT)


关于这两个理论, 可以看这里

* 认知灵活性理论

** 核心逻辑推演

1) 学习是对概念理解的主动建构过程。
2) 训练必须帮助学习者克服过度简化的解释。
3) 过度简化的解释会通过形成「误解网络」和「知识护盾」来自我强化和维持。
4) 高级学习是指在特定领域内灵活运用知识的能力。
*因此*, 通过逐步增加复杂性的教学方法不利于实现高级学习。
*因此*, 强调多个案例和概念之间沿多个维度的相互联系, 并使用多种、高度结构化的表征方式, 能够促进高级学习。

** 经验基础

对具有概念复杂性的主题进行的研究 (以医学生为研究对象) 。
对知识护盾和难度维度的验证性演示。
对学习者倾向于通过站不住脚的复杂性简化 (即简化偏见) 来进行过度简化的验证性演示。
关于使用多种类比的价值的研究。
对学习者倾向于将不规则事物规则化处理, 从而导致知识无法迁移到新案例的验证性演示。
对学习者倾向于将概念脱离背景处理, 从而导致知识无法迁移到新案例的验证性演示。
对学习者倾向于扮演被动接受者而非主动参与者的验证性演示。
关于学习者倾向于过度依赖通用抽象概念的假设, 这些抽象概念可能与具体经验实例相距甚远, 以至于显然无法应用于新案例, 即导致知识无法迁移到新案例。
概念的复杂性和案例之间的不规则性给传统的教学理论和模式带来了挑战。
先简化后逐步增加复杂性的教学方法, 可能通过助长过度简化的理解和知识护盾的形成, 从而阻碍高级知识的获取。
强调回忆性记忆的教学方法, 对于促进推理理解和高级知识获取 (知识迁移) 并无助益。

** 该理论的其他主张

高级知识的获取 (从学徒到熟手再到专家) 取决于达成更深层次理解并灵活应用知识的能力。
高级学习的障碍包括: *复杂性*​、​*交互性*​、​*情境依赖性*​以及​*结构不良性* (即概念组合模式的不一致性) 。
认知灵活性包括调动小型的、预先编译好的知识结构的能力, 这种「适应性图式组装」过程涉及整合与更新, 而不仅仅是回忆。
 (对于复杂且结构不良的领域而言) 在学习中, 从不同的概念和案例来源主动「组装知识」比检索现成的知识结构更为重要。
错误的理解会相互叠加, 形成误解网络。对基本概念的误解会以系统化的方式相互关联, 使得每一个误解都更容易被接受, 且更难以纠正。
具有高度相互联系性的表征方式, 往往能起到「消除误解的正确知识」的作用。
认知灵活性是指能够从不同的概念和案例视角来表征知识, 并根据当前问题的需求, 从中构建出一个适应性的知识整体的能力。

* 认知转型理论

** 核心逻辑推演

1) 学习包含对心智模型的精细阐述和更新替换。
2) 心智模型是有局限的, 并且包含知识护盾。
3) 知识护盾会导致错误的诊断, 并使人能够忽视掉不符的证据。
*因此*, 学习也必须包含「反向学习」 (unlearning) 的过程。

** 经验基础与主张

对科学家推理过程的研究
对有缺陷的「仓库式」记忆隐喻及其衍生的教学理念 (如强调记忆事实、练习加即时反馈、结果反馈) 的批判。
科学学习领域的研究表明, 误解是如何导致错误的。
关于科学家和学生面对异常数据时不同反应的研究。
「认知冲突」方法在引发概念转变方面的成功实践。

** 该理论的其他主张

心智模型是简化且碎片化的, 因此是不完整且有缺陷的。
学习即是心智模型的完善过程。心智模型提供因果解释。
专家比新手拥有更详尽、更复杂的心智模型。专家拥有更准确的因果心智模型。
存在缺陷的心智模型是学习的障碍 (即知识护盾) 。
学习既通过「感知构建」 (发现、反思) 发生, 也通过教学发生。
心智模型的精炼过程至少包含某种程度的「反向学习 (un-learning) 」 (顺应；重构；核心概念的改变) 。
心智模型的完善有时可能只是增加了错误模型的复杂性, 使其更容易让学习者为不一致或异常的数据找到理由开脱。
学习是非连续性的。 (当有缺陷的心智模型被替换时, 学习取得进展；当一个模型被完善且变得更难以被证伪时, 学习趋于稳定。)
人们拥有多种碎片化的心智模型。「核心」心智模型是因果叙事。

* CFT-CTT 合并理论的核心逻辑推演

1) 学习是知识的主动构建过程；是对心智模型、因果叙事或概念理解的精细阐述和更新替换。
2) 所有心智模型都是有限的。人们拥有各种碎片化且往往是简化性的心智模型。
3) 训练必须帮助学习者克服简化性的解释。
4) 知识护盾会导致错误的诊断, 并使人能够忽视掉不符的证据。
5) 简化性解释会通过形成误解网络和知识护盾来自我强化和维持。灵活的学习涉及概念与情境细节之间的相互作用, 这种作用在特定领域内的应用案例中展现出来并受到其影响。
因此, 学习也必须包含反向学习和重新学习的过程。
因此, 强调多个案例和概念之间沿多个概念维度的相互联系, 并使用多种、高度结构化的表征方式, 能够促进高级学习。

* 两个重要启示
1. 首先, 专业技能文献中的​*一切*​都难以推广应用。
   有些方法在某些领域效果显著, 但在其他领域则不然。
   最终的检验标准在于实践应用: 如果你尝试将某种方法付诸实践却未获成功, 这并不一定意味着该方法本身不好, 仅仅说明它不适用于你的特定情境。你越早学会接受这一点越好。

2. 其次, 作者们特意指出, 关于训练的许多事情可能​*永远*​无法确知。
   例如, 在真实世界的复杂情境中, 几乎不可能分离出导致训练成功的确切因素——然而, 真实世界恰恰是我们最终希望训练能够奏效的地方。干扰变量实在太多了。
   而且事实是, 我们也不能反过来进行完全受控的实验——让基于实验室或课堂环境的训练真正起作用也极其困难。


* 启发

我或许应该维护一个疑难库, 维护我在开发中遇到的那些疑难案例, 以及我是怎么解决它们的
