#+title: Cognitive Flexibility Theory
#+author: SOV710
#+date: <2026-01-25 Sun>

*在商业和投资领域, 你所遇到的一切几乎都是全新的、独一无二的, 此时你该如何学习? *

这是一个关于「认知灵活性理论」的文章。该理论旨在探讨如何在结构不良领域中进行有效学习。

因此, 结构不良领域中的专家必须不断应对新颖的情境, *他们遇到的每一个问题, 都与以往见过的任何案例不尽相同。*

这类领域的例子包括医学——其中有诸如「心脏病发作」之类的概念, 但心脏病发作在不同患者身上的表现却差异巨大——此外也包括商业、软件工程和投资等领域。

* 从他人经验中学习的最佳方式

经验按理说是最好的老师, 但既然万物总在变化之中, 你也不太可能在自己的人生中经历完全相同的两件事情; 「历史不会重演, 你何必浪费时间读商业史? 」

但, 一个事实是: 老练的专家要比新手更善于处理新奇事物。我们可以将问题拆分成以下几部分:
- 专家面对新颖情境时采取了什么方法?
- 我们能否将这种能力教给新手?
- *当专家们对问题进行总结归纳时, 他们究竟在做哪些与众不同的事情?*

能为这些问题提供最佳答案的理论, 叫做认知灵活性理论 (Cognitive Flexibility Theory) , 最初由 Rand Spiro、Paul Feltovich、Michael Jacobson 和 Richard Coulson 在 1988 年的一篇论文中提出。

** 传统学习理论 ——「图式发展」(schema development)

当你读到国际象棋中的「组块」 (chunking) 概念时, 你实际上接触的就是一种图式学习理论。

这种观点的通俗版本大致如下：当你学习国际象棋时, 你本质上是在头脑中存储数以百万计的棋局模式。这些模式形成了你可以在记忆中操纵的「组块」, 因此, 当你在进行一场关键棋局时, 你会提取这些预封装的图式来指导你的决策。

需要注意的是, 这些图式不一定能被有意识地提取——在最高技能水平上, 图式的提取通常表现为直觉。一个著名的现象是, 国际象棋特级大师们倾向于将他们对棋盘局势的这些「感觉」描述为「力之线 (lines of force) 」、「正在形成的弱点区域 (developing areas of weakness) 」或其他类似难以言传的隐式概念

毫无疑问, 现实世界中的很大一部分专业技能​*确实*​是这样运作的。例如, 如果你是一位作家或计算机程序员, 你的头脑里很可能储备了一堆组块化的技巧, 以便你随时在写作或编程时调用。

但是, 这​*依然不够*​。人们察觉到需要一种补充性的理论, 来解释在​*结构更为不良的领域*​中知识是如何显露和使用的

** CFT —— Cognitive Flexibility Theory

*CFT 是一种学习与教学理论, 旨在促进知识和经验在某个领域的任何非常规方面的适应性应用*

或者, 对于那些新遇到的案例大多是非常规的领域而言, CFT 应作为该领域的​*主要认知世界观*, 只有在探测到规律性时才切换到更简化的世界观, 而不是反过来

*例子*:
在商业决策中, 你常常必须在头脑中权衡大量的变量, 而这些变量又高度依赖于你的具体情境。你身处哪个行业? 你的产品线处于何种成熟阶段? 你的现金流状况如何? 相似的商业策略, 会因为公司成熟度、融资渠道、组织结构 (这决定了你的能力) 以及你所处市场的竞争态势等因素, 在实践中呈现出截然不同的面貌。

*结论*:
越是结构不良的领域, 「自上而下」的结构为知识应用提供的指导就越差。

在一个结构不良领域 (即一个案例本身是多维的, 且与下一个案例之间呈现不规则关联的领域) 中, 知识在具体案例中的应用是无法通过一般原则预先规定的。

在一个结构不良的领域中, 一般原则无法捕获足够多的案例结构动态；应对高度多样化的新案例时, 灵活性越来越依赖于从先例中进行推理

*启示*:
在结构不良领域中学习, 阅读历史案例是​*核心*

我们需要改变我们对于在这类领域中学习的看法, *案例才是一切*

在任何结构不良领域中, 你无法轻易地从任何特定案例中推广出普适原则；当你应用概念时, 从该概念过往的具体表现形式进行推理, 比直接从抽象原则本身出发要更容易！

*CFT* 的内容:
专家会通过以下两种方式来应对新情况:
1. 首先, 他们会在新情境中复用旧案例和概念的片段
2. 其次, 具备适应性专业技能的实践者似乎都共有一种相似的世界观。


** 适应性世界观

尽管每一个新颖的案例 (根据定义) 都是独特和全新的, 但存在着一组元特征 (meta-features) , 能够帮助专家理解并适应这种新颖性。

- 本体论特征 (Ontological features)——即关于世界如何运作的一系列信条。
- 认识论特征 (Epistemological features)——即关于如何学习和理解这样一个世界的一系列信条。


这听起来有些高深, 但实际上相当容易理解。想象一下心脏病发作的情景。如果你和我一样 (即不是医生), 你可能会默认总结一个可视化的心脏病发作「原型案例」。这很可能是一些常见心脏病症状的集合, 比如一个男人或女人突然倒地, 捂着胸口或手臂, 脸色发青。

然而, 专家医生头脑中并​*没有*​这样的原型案例。他们明白原型案例是​*简化性*​的——也就是说, 你会不自觉地试图将现实中看到的情况, 映射到你脑海中那个想象出来的理想化心脏病发作模型上。相比之下, 专家医生拥有的, 是一个更庞大的、可供比较的​*案例集合*​。他们明白心脏病发作的临床表现 (case presentation) 变化极大——并且取决于患者独特的病史、种族、年龄和性别。毕竟, 有些心脏病发作最初可能表现为消化不良, 有些则可能持续数天。


适应性世界观的关键在于接受以下两点：

1. 在一个结构不良领域中, 观察到的现象往往有多重诱因。事实上, 同一个案例可以从许多截然不同但一样有效的角度来看待; 概念的实例化可以呈现出多种形式。 (这是该世界观的本体论特征) 。
2. 因此, 学习这样一个领域要求实践者抵制将一切现象简化为单一解释或单一原型案例的倾向。 (这是该世界观的认识论特征) 。
