#+title: Refold Roadmap
#+author: SOV710
#+date: <2026-01-19 Mon>

* Stage 0: Refold Philosophy

** Stage 0A: 方法

*** 0A1: 语言习得

习得和学得的区别, 不再赘述

*** 0A2: 路线图概述

*Stage 1*: 只做第二语言输入, 不做输出
你会用到一些传统的语言学习工具, 比如抽认卡、词汇表和语法手册, 但用法和传统截然不同
你不需要用这些工具来学会如何表达, 你只需要用它们来理解素材内容就可以了。学习的方向只有一个, 那就是从目标语言到母语。不去尝试说或者写, 也就是不做「输出」。

*Stage 2*: 把注意力集中在有意识地学习沉浸材料上, 实际上是在学习和实践之间建立了一个良性循环, 加快了语言习得的速度
开始时, 选些更容易理解的媒体, 再逐渐提高难度, 直至能听懂面向成年人的母语级别内容。从简单的媒体开始, 不仅能打下牢固的基础, 还能让你在沉浸学习中找到乐趣
当你的理解能力达到一定水平后, 就缩小学习范围, 专攻语言的某个小领域。一旦你对这一小块领域的理解接近完美, 就可以开始开口说话了。

*Stage 3*: 该准备输出了。之前你都是通过输入来建立潜能池, 下一步就是把这种潜能转化为实际输出能力。
你会刻意把自己放到需要写作和说话的场合。这样做会迫使你的大脑在已经习得的语言池子中搜寻, 使词汇和短语随时可以用来输出。
当然, 也有时候你会觉得不知所措, 一时说不出合适的话。这正好揭示了你语言习得中的不足。有了这个发现, 你可以针对性地多听、多看, 弥补这些不足。这种输出和输入的相互作用, 能让你迅速地达到基础流利程度。

*Stage 4*: 到这个时候, 你习得的语言能力会达到 B2 级, 无论是听力理解还是口头交流, 都能游刃有余。
想要突破 B2 级？在更多的分支主题上重复阶段 1 和阶段 2。每重复一次, 过程就变得更简单。不用多久, 你就能达到 C1、C2 或者母语般的流利程度。

好的开始, 是成功的一半

坚持就是胜利的另一半

** Stage 0B: 心态

*** 0B1: 享受语言

第一, 享受沉浸的内容, 而非形式; 当你忘我地沉醉到材料中时, 语言知识会退居幕后, 你会进入心流状态

如果你没有投入其中, 你就会走神, 也就无法习得任何东西。无聊会导致你的大脑完全过滤掉所输入的语言内容

第二, 不要强迫自己沉浸学习不感兴趣的内容。

如果你对某个电视剧或书籍感到厌烦, 那就换一个。强迫自己接触不喜欢的内容只会让动力消逝殆尽

有一句忠告: Refold 方法只是一个指南。追随你的兴趣, 比死守我们的计划更为重要。如果你在到达「阶段 2C: 阅读」之前就迫不及待地想读一本书, 那么, 请放手去读吧, 没有必要等待。你享受这些内容的内在动力, 会比任何学习方法, 包括我们的, 更能促进语言习得。

*** 0B2: 容忍模糊感

在无法理解外语时, 我们会有种无所适从的感觉。面对这种难以理解的语言输入, 我们很自然地会觉得自己很蠢, 感到挫败, 甚至自闭, 这些负面情绪不仅会打击你的学习动力, 还会阻碍你的大脑吸收语言, 这种现象被称为「情感过滤器假说」。

单靠背诵词汇和语法规则, 你并不能真正准备好应对实际语言使用。在现实生活中, 人们的说话方式各不相同, 他们可能会含糊其词, 使用方言和俚语, 或者快速说话, 甚至模糊不清。要想理解他们, 你也必须参与其中, 自己摸索。

学习语言最艰难的部分, 就在于接受自己的无力感, 以及容忍自己无法理解的语言带来的模糊感。

*如何增强对模糊感的忍耐力？*

首先, 不要再自我贬低。不要再说「我永远也搞不明白」, 你现在还不懂, 并不代表你永远都不会懂。你越是自我贬低, 心情就会越糟, 学习的难度也会随之增大。

换个思考角度看问题: 问题的关键不在于你「没理解」, 而在于你无法接受自己的不理解。不理解其实没关系, 这是学习过程中很自然、也很必要的一部分。试着跟它和解。

别每个生词都查字典。当你因为模糊感而觉得难受时, 你可能会忍不住查阅每个不知道的单词。但你要学会克制这种冲动。频繁的查阅会打断你的学习节奏, 影响大脑对语言的吸收。

慢慢来。你还不习惯不懂的感觉, 甚至可能会头疼。给自己一些时间, 慢慢来, 逐步提高忍耐力。过不了多久, 你就能轻松看完一小时的电视节目。

欣喜每一个小进步。可能你听懂了一个新词, 或者一个句子。每当有这样的时刻, 记得为自己点赞。

最重要的是: 记住要享受其中。

** Stage 0C: 核心活动

*** 0C1: 主动沉浸

主动沉浸, 就是将全身心投入到你正在接触的内容中, 无论是听音频、看视听媒体, 还是读文字材料。

*主动沉浸是语言习得中【最重要】的一环*

当你刚开始沉浸时, 你的大脑可能会忽略大部分信息, 因为它认为这些信息并不重要。当你专心致志地将注意力集中在目标语言的内容时, 你的大脑会知道它需要开始关注了。

你也许觉得把时间花在观看目标语言的电视节目上, 是诡异且没有成效的事情。请放心: 这并不是虚度时光, 这正是语言习得发生的地方。即使有的内容你几乎完全无法理解, 你的大脑仍在积极工作, 寻找规律, 验证假设, 构建你内在的语言机器。

*** 0C2: 被动收听

正如上一篇文章指出, 主动沉浸是语言习得中最重要的活动。遗憾的是, 对于忙碌的人来说, 很难在日常生活中找到大把的时间来进行主动沉浸。幸运的是, 在日常生活中, 你有很多机会来​*被动收听*​你的目标语言, 比如做饭、打扫卫生、上下班通勤或锻炼身体等不太耗脑子的活动时。

我们称之为「被动收听」, 因为你并没有全神贯注在内容上, 你的注意力被分散在各种活动之中。

我们建议你反复听那些你已经主动沉浸过的内容。因为重复能让你的大脑有机会进一步吸收和分析语音和词汇, 这对大脑有益。遗憾的是, 重复往往乏味, 而无聊是学习的敌人。被动收听则是一种无感的重复, 让你的大脑有机会再次收听你已经主动沉浸过的内容。

最初, 你可能有很多内容都听不懂, 因此学会容忍模糊感并坚持听下去很关键。听你已经观看过的内容可以帮助你保持兴趣, 因为即使你听不懂, 你也会记住故事情节。

开始时, 你应该专心听你目标语言的声音。你可能感觉不到有什么变化, 但实际上你的大脑正在无意识地学习解析外语声音。

随着你的词汇量和听力能力的提高, 你会对被动收听的内容有更深的理解。最终, 你将能够听懂全新的内容, 如播客、有声书和谈话节目。

记住, 无聊是学习的敌人。如果你对被动收听的内容感到无聊, 那就换些更有趣的内容吧！

*** 0C3: 主动非沉浸学习

*启动效应*: 当你学习一个新词时, 你的大脑就像在「心理字典」中为它开辟了一个新词条。这个词条促使你的大脑在沉浸学习中注意这个词, 每当你遇到这个词时, 你的大脑就会把一点点补充信息关联到这个词条中, 当你多次见到这个词, 你的大脑就可以根据积累的信息推测出这个词的含义和用法。

*理解*: 别忘了, 我们通过可理解输入习得语言。当你记住一个词的含义时, 你就会在心理字典的词条中为它加上定义。有了这个定义, 你接收的输入就变得更容易理解了。你理解的越多, 你习得的就越多。

*SRS/Anki*: 最出色的记忆保持系统

* Stage 1

** Stage 1A: 配置好工具, 养成好习惯

*** 1A1: 主动沉浸

让大脑真正搞懂目标语言, 需要花费数百小时的时间去观看、收听和阅读。你在目标语言中沉浸得越久, 进步就越快。因此, 你需要削减接触母语内容的时间, 给目标语言内容腾出空间。

首先设个小目标, 每天至少花半小时主动沉浸在你的目标语言中。

在这个阶段, 你应该探索目标语言中可看的视频内容。涉猎不同类型的媒体: 卡通、动漫、连续剧、话剧、电影等, 到处逛逛看, 尝试不同的题材, 熟悉那些常见的套路。如果碰上了合眼缘的导演、编剧或者演员, 那就多关注他们的作品。

敢于尝试一些在你母语里从没碰过的内容。多了解一下这个文化, 说不定能找到一些意想不到的好东西。

当你发现你真正喜欢的东西时, 记得做个标记, 在阶段 2, 你就可以从这个清单里的沉浸内容直接学起了。

一些启动小窍门:

- 新开个 YouTube 账号, 充分利用上 YouTube 的推荐算法
- 看带有母语字幕的视频, 让自己在养成这个新习惯的同时, 享受沉浸的乐趣

*接受模糊感*:

语言学习中最难的部分之一, 就是不理解你的目标语言, 这会让你觉得自己很笨, 情绪低落, 甚至焦躁不安。但别因此气馁。这是每个人都要经历的自然过程

这种负面情绪会妨碍你学习新语言。这一现象有个学名, 叫做「情感过滤假说」。你得调整好自己的心态, 这样才能愉快地沉浸在新语言中。

这个阶段是无法跳过的。处理这种模糊感是语言习得过程中必经之路, 但你别担心。时刻提醒自己这只是暂时的, 你终将走出这个阶段

*如何接受模糊感*:

一开始, 用母语字幕没啥不可以, 这样至少不会让你气馁。尽管母语字母并不能直接帮助你学习语言, 但它能帮你养成观看目标语言内容的习惯, 同时也能积累下一些以后可以重看的内容。一旦你适应了这个阶段（1A）里规定的日常习惯, 就应该逐渐放弃母语字幕

一旦你去掉了母语字幕, 就会更难跟上你所看节目的情节, 因此, 你需要学会容忍不知道到底发生了什么的模糊感。以下几点建议或许能帮你适应这种模糊感

1. 限制使用母语字幕

试着控制看字幕的次数。比方说, 在看一个 30 分钟的电视剧时, 你最多只看十行字幕。然后你逐步减少这个数字, 直到能看完一整集也不用去瞄一眼字幕。

2. 重温老剧

 大家总有那么几部喜欢到能背出台词的剧, 比如《口袋妖怪》, Netflix 上有多种语言版本。试着用目标语言去看, 因为剧情你已经了如指掌, 就算听不懂, 你也能维持对剧情的兴趣。这样, 你就能集中精力去理解语言, 而不是去揣摩剧情了

3. 看简单点的节目

儿童节目和情景喜剧通常有丰富的视觉元素, 方便你理解。即便你听不懂对话, 也能跟得上剧情。

这也可以是一个观看具有文化意义节目的机会, 这些节目常常会在其他媒体和日常生活中被提到。简单搜一下, 就能找到和你年龄相仿的母语者以前常看的节目。

一句忠告: 如果你对儿童节目没兴趣, 就别勉强自己。乐子比理解更重要。

4. 把它变成游戏

为了在面对费解的内容时保持兴趣, 你可以自己创造一些小游戏:

1) 专注于发音。

试着把注意力放在语言的声音上, 而不是放在意思上。在 Stage 1B1: 发音规则中, 你将了解到目标语言中会存在一些你大脑还听不懂的发音, 试着去听这些声音。

2) 仔细听这些词。

试着判断一个单词在哪里结束, 下一个单词从哪里开始。

在头脑中记下两个词混在一起时听起来是什么样子。

3) 寻找认识的单词。

当你学习词汇时, 在你的沉浸中找出这些词。

看看你能认出多少个熟悉的单词。

*** 1A2: 养成被动收听习惯

你的大脑要大量的音频输入来熟悉目标语言的各种声调和语速, 尤其是刚入门时, 可能得听个几遍, 大脑才能开始分辨这些声音, 熟悉它们。被动收听就是为了能让你有大量机会重复听, 反复听。

在整个语言习得过程中, 被动收听都是核心活动, 所以, 一开始就要建立好合适的工作流。

为了有效的被动收听, 你得培养两个好习惯:

**** 在做无需动脑的事情时收听


现在就花点时间想想, 你一天里哪些时候能够把被动收听融入进来。比较常见的机会有:

- 在通勤或旅行的路上
- 在散步或锻炼的时候
- 做饭、扫地或是搞其他家务的时候
- 在早晨的例行活动中, 如遛狗或吃早餐时
- 在睡前的例行活动中, 如刷牙或入睡时

提前做个计划, 看看啥时候适合被动收听, 并准备好你需要的工具（比如, 手机里整个音频列表, 再弄一副耳机）, 一个简单的办法是, 打开手机上的 YouTube 或 Netflix, 听你已经看过的内容。

**** 让被动收听更简单


为了让这个习惯尽可能轻松, 关键是要准备好一份随时能被动收听的播放列表。

虽然被动收听 Netflix 或 YouTube 上的视频很容易, 但这两个应用需要你手机保持解锁状态。作为替代, 我们推荐你在手机里创建一个永远在循环的本地播放列表。

长时间被动收听同样的内容可能会让人生厌, 所以, 最好定期更新播放列表, 淘汰一些陈旧的内容。每隔一两周, 抽空将新音频加入手机, 以便随时随地都能收听。

-----

**** 内容推荐

选择被动收听内容的首要目标是找到能引起你兴趣的东西。听你已经看过的电视节目的音频有助于此, 因为你已经了解剧情。

或者, 听听你喜欢的小说的目标语言有声书。要是你对故事了如指掌, 即便只认识几个词, 跟着听也相对容易。

*音乐不是被动收听的好选择*​。尽管娱乐性强, 但其学习价值不高。歌词经常让人困惑, 而且容易误解。你自己听母语歌都能听错词, 何况是别的语言。

要是你就喜欢听歌, 那目标语言的歌也比啥都没有强, 但最好还是多听听有对话或者叙述的音频。

如果你对正在听的内容感到厌倦, 那就换点别的。随你的兴趣走。

*无聊是语言学习的敌人。*

**** 如何对「胡言乱语」保持兴趣

当你第一次开始被动收听时, 你不会理解任何东西, 你的思绪会飘忽不定, 这没有关系！这是一种自然的反应, 你的大脑会过滤掉「不重要」的声音, 所以你很可能会感到无聊并跳到另一个思绪里。

要让大脑不走神, 试试以下几招:

- 专注于听声音而不是听单词。
- 试着听出一个词的结束和另一个词的开始。

暂时别纠结意思。

当你学习新的词汇时, 泛听音频以尝试听到学习中的新词汇。

*** 1A3: Anki 初级配置教程

略

** Stage 1B: 学习基础知识

*** 1B1: 发音规则

幼儿具备准确听出人类所有语言中每一个音素的能力。随着年龄增长, 大脑为了更高效地处理母语, 会放弃识别不必要的音素。这意味着, 你现在可能无法察觉到目标语言中的某些音素。在你有机会注意到这些音素之前, 你的大脑就已经将其过滤掉了。然而, 这并非无可挽回。大脑能重新学会识别这些曾经认为不必要的音素。

如果你学习一下外语的发音规则, 就能更快地听出这些发音。我们的目标是达到可以开始学习词汇的程度, 所以你只需要学习目标语言声音系统的基本知识。高深的发音规则等到阶段 4 再说。

**** 如何学习发音

首先, 上网搜一搜你要学的那门语言的读音规则。查一查都有哪些元音和辅音, 嘴巴怎么张怎么合才能发出这些音。别只看一个网站, 多找几个参考一下。寻找那些既能让你听到这些音, 又能展示如何发这些音（口型、舌位等）的资料。

如果你的目标语言还有其他核心的语音特征, 如力重音、音高重音或声调, 也一并学习了解。

在主动沉浸的过程中, 也别忘了特别注意这些发音细节。可以参考 1A 主动沉浸中描述的方式练习。

*** 1B2: 书写系统

成年人学习语言, 最行之有效的方式就是在培育听力理解的同时培育阅读理解。

在开始阅读之前, 你需要学习目标语言的书面文字。

**** 只需打个基础

这个阶段的目标, 就是把文字学到能认词、看懂语法的程度。至于快速、流利地阅读, 那是之后的事。

要花多长时间, 因人而异, 也得看你要学的是哪种语言。比如说, 讲英语的人学西班牙语可能就几分钟就能上手, 但要学中文, 那可得花上几个月。

**** 错误发音

对于那些与你的母语使用相同文字的语言, 你会自动将相同的符号与母语中的发音联系起来, 这可能会导致你在脑中默读时出现发音错误。

别焦虑, 这个问题以后自然会改正过来。只需明白, 这种情况肯定会发生。请确保你清楚哪个字母对应哪个发音。

**** 接受自己的不足

对于那些用一套完全不同的字母系统的语言, 学习阅读可能会觉得吃力, 感觉处处都束手束脚。就像孩子学习阅读一样, 你一开始只能一个字一个字地拼读, 而不是以一个个意群来感知整个单词和短语。

特别是在你不确定应该怎么念某个词的时候, 可能会觉得特别沮丧。不过别太焦虑——随着时间的推移, 这个问题会自然解决。

**** 非表音文字

像汉语这样的语言, 并没有字母表。每个字都是一个寓意于形的小图画。这些图画一旦组合, 不仅构成了更复杂的图画, 意义也更加丰富。

请参考针对特定语言的指南, 学习如何理解这些基于图画的书写系统。

学会用你的目标语言打字也很有帮助, 这样查单词会更方便。

** Stage 1C: 快速启动你的理解力

*** 1C1: 语法

跟世界语、克林贡语、精灵语这些人造语言不一样, 大多数语言都不是精心设计出来的, 它们都是历经千锤百炼, 几千年的无序演变才有的, 所谓的「规则」根本不存在。

学校教育让我们误以为, 只有遵循语法规则才能正确使用语言。此乃谎言。语法规则其实是事后对人们实际语言用法的归纳总结。

**** 我们真的需要学习语法吗？

简短的答案是: 不需要。你的大脑可以自己悟出语法, 不需要刻意去学。可惜, 这个过程真的很慢。

刚开始学习语言时, 了解一些基础的语法有助于加快你的理解。简单来说, 语法就是拐杖, 等到你的大脑可以自然而然地理解这门语言, 这个拐杖就可以丢了。

因为你只需要语法来进行基本的理解, 所以没必要去钻研高级语法那些复杂微妙的地方, 这些东西, 你在沉浸学习中自然会掌握。

因此, 只管抓紧学那些最基本、最直接影响你理解沉浸内容的语法点就行了。

**** 如何学习语法

一口气大量学习语法枯燥无味, 所以我们建议在沉浸学习和词汇学习的同时逐步学习语法。

每天花 10 到 20 分钟学习目标语言的基础语法概念。

由于你不需要深入了解细微的语法概念, 所以选哪本语法书其实没大差别, 只要是能帮你了解目标语言基础语法的材料, 那就够了。

动动手指, 网上搜索一下, 看看有哪些适合初学者的语法指南。不论是 YouTube 教学视频, 网课, 独立网站, 入门教材, 还是语言学习应用, 挑一个你喜欢, 符合你生活节奏的就行了。

要是碰到某个让你摸不着头脑的语法问题, 那就跳过去, 继续往下走。通过在沉浸学习中不断接触, 你会逐渐对语法有一种直观的理解。要是实在觉得不对劲, 等你有了更多经验后, 再回头去翻翻语法书也不迟。

别忘了, 学语法的最终目的是为了让你理解目标语言, 【不要】硬着头皮按语法规则去说或写。你将通过沉浸学习培养这两种能力。

**** 学什么

学习语法的目标是为了理解。要想理解一个句子, 你需要能做到以下几点:

- *把单词分清楚*: 有的语言把单词粘一块儿, 或者单词之间没空隙。学点语法, 你就能知道哪儿断句
- *看清主语是啥*: 你将通过词汇学习来学习名词, 但大多数语言都使用代词和连接词来隐含表示主语, 语法学习将教会你代词和基于主语的变位的基本知识
- *弄懂主语碰上啥事了*: 和语法无关, 你将通过学习动词词汇培养这个能力
- *搞清楚这事啥时候发生的*: 了解时态对看懂故事至关重要, 但只需要掌握语法的基本知识就好, 不需要细究时态的微妙之处, 我们的目标是先打开理解的大门

*** 1C2: SRS 最佳实践

略

*** 1C3: 词汇

使用间隔重复系统（SRS）来学习目标语言中最常出现的 1500 个单词。

有研究估计, 在英语中, 大约 2000 个单词就覆盖了日常对话中约 94% 的内容。如果词汇量达到 5000, 这个数字就会跃升到将近 99%。不同的研究对不同的数据进行分析, 得出的数字各不相同, 但也大同小异。

虽然这个百分比因语言而异, 但记住 1500 个单词将为你打下坚实的基础。

然而, 知道 1500 个单词并不能自动转化为理解, 所以如果你仍然不理解, 不要感到惊讶。你可能会理解对话中 90% 的单词, 但要理解一段对话的完整含义, 还需要沉浸其中, 并将这些知识用于实践。

**** 如何开始

运用间隔重复系统（SRS）学习常用词汇, 大致有两个方法。

- 直接用别人做好的词汇牌组。
- 自己找个高频词表, 动手做卡。

用别人现成的牌组是最快的开始方法, 但高质量的牌组并不好找。大多数牌组都是用软件生成的, 没有针对高效学习进行筛选。这些牌组常常包含一些与你要实现的目标——即快速开始沉浸学习——不太相关的词汇。还可能出现翻译不准确、音频错误或缺失的问题。

自己做卡片虽然初期需要花费更多时间, 但如果你找不到精选的牌组, 那么这点儿功夫是值得的。

两种方式都可以, 选一个你觉得合适的就行。

请记住, 1500 个单词并不是什么硬性规定。即使你只学 1000 个词, 也完全没问题。别忘了: 背单词是学得, 而不是习得。你只需要建立一个基础词汇量, 以加速你对沉浸内容的理解。你追求的不是完美, 而是够用——够常见的词, 记得够牢固。

**** 理解, 而不是输出

学词汇的根本目的, 就是为了在沉浸学习中识别并理解这些单词。要锻炼这种识别能力, 你只需要学习正面为目标语言的卡片。这类卡片常被称作「理解卡」或「认识卡」。

在传统的学习方式中, 一般会让你背出目标语言的单词, 或者从你的母语翻译过来。这种卡片就叫「输出卡」或「回忆卡」。这种类型的卡片可免则免。如果你碰到带有这种「生产卡」或「回忆卡」的牌组, 大可直接删掉。

**** 进阶

记住, 【没必要】在进入阶段 2 前就硬啃完最常用的 1500 个词汇。

进入阶段 2 后, 你将建一个新牌组, 开始在你的沉浸内容中做词句挖掘。你可以同时学习这两个牌组, 也可以抛开入门牌组, 专注于词句挖掘。怎么选, 全凭你。

* Stage 2

** Stage 2A: 克服难度陡坡

刚开始沉浸时，你几乎无法理解任何内容。所有的沉浸内容都像遥不可及的高峰。一开始，理解能力的提升是一个难度陡坡。你得先缩小沉浸学习的范围，挑一部分语言内容来专攻，这样能更快地提升你的理解能力。

*** 2A1: 领域

*** 2A2: 可理解性的影响因素

*** 2A3: 可理解性的媒体类型索引

*** 2A4: 理解等级

*** 2A5: 主动沉浸的类型

*** 2A6: 沉浸学习指南

*** 2A7: 基础词句挖掘

** Stage 2B: 拓宽你的领域

*** 2B1: 沉浸学习指南

*** 2B2: 高级词句挖掘

*** 2B3: 自然单语过渡

** Stage 2C: 精通理解

*** 2C1: 沉浸学习指南

*** 2C2: 纯听力（选修）

*** 2C3: 如何阅读小说（选修）

*** 2C4: 结构化单语过渡

* Stage 3

** Stage 3A: 为输出做准备

*** 3A1: 开始输出

*** 3A2: 活动指南

*** 3A3: 认领语言家长

** Stage 3B: 刻意练习

*** 3B1: 语言激活

*** 3B2: 输出问题排查

*** 3B3: 发音训练

*** 3B4: 活动指南

** Stage 3C: 开口说话

*** 3C1: 能力与表现

*** 3C2: 培养口语能力

*** 3C3: 口语练习

*** 3C4: 口语问题排查

*** 3C5: 活动指南

* Stage 4: 超越流利
