#+title: Henan Province: Pain
#+author: SOV710
#+date: <2026-01-03 Sat>

[[https://www.bilibili.com/video/BV1huqmBGEYo][原视频地址]]

主题: 痛苦

河南在国家现代化进程中掉队了

更多的是文化方面

总而言之: 为了高速发展，提供了近乎无限的生命材料

* 矛盾
中国一定绕不开河南，因为这里是中原

矛盾之一：河南人多，但是完全没有政治话语权

他们的政治诉求无法变成影响力

农业上，河南是全国的粮仓，这导致河南没有工业化，完全没有工业积累

文化上，虽然河南在历史上有很重要的地位，所谓中原就是指河南，华夏文明的发源地，非常深厚的文化遗产

但是在当代话语体系下面，在刻板印象里面，河南承受了太多的地域污名化，河南的地域歧视和东三省一样都是 T0 级别的

历史上，在战争年代还是在经济建设上，河南是动员最强的地方，但是河南在利益分配的时候永远是最末端的那一个利益链条

河南的失败不是偶然的，这是因为河南是整个国家缓冲失败、承担风险的一环，它的落后与失败，不是国家的失败，这是一种成本转嫁和风险分配，这是国家在有意识的利用河南作为代价，去发展别的地方

那么我们要问，为什么偏偏是河南呢？为什么一个新政权为什么要在这个地方高强度的进行风险提取。

因为这个地方的社会成本和政治阻力最小，因为这里是黄泛区，高压不稳定是常态。晚清至明清时期，这里是决口改造的重点区域，1855 年咸丰年间，黄河北起开始，灾难就开始了。

所以，你会发现地域歧视会集中在河南，安徽背部，苏州北部，他们都是黄河淹的地方。最具决定性的是在 38 年花园口决堤。近 90 万人直接死亡，长达 8 年的黄河泛滥期，这个实在是太离谱了。

1942 年由于旱灾蝗灾，河南大饥荒。

在这个背景下，旱灾，蝗虫，战争共同作用，大概有三百万人死去。

这个重复的灾难，把土地反复格式化了，这个地方的传统宗族被大大削弱了，这个地方几乎没有历史，大规模的移民成为了常态，贩卖子女、易子相食成为了常态。能活下去是最重要的，什么东西都不重要了。社会秩序崩解了，所以地方的土匪和自卫团体出现了，政府的统治力在基层非常薄弱，土地上的民众长期生活在生存边缘的状态，所以他们对于外部的干预是习以为常的，土匪抢劫他们他们是直接接受了，在这个背景上，国家介入了。

历届政府，比如晚清北洋的做法是以工代赈，并且把国家权力渗透到基层。清朝的时候就兴办的河工去吸纳灾民，取代直接的钱粮赈济。民国政府发扬了这个，多次组织了修复水利为主的工赈。

干预是强制性的，但是民众接受这种强制性。在灾难时期，政府控制了唯一的救命资源，工作机会，因为有工作才有粮食，才能活下去，把流散的灾民组织起来了，纳入了国家的管理体系。大规模的社会动员，强化了政府对于地方的控制能力。国家权力高频次地干预社会，这是这个时代的基础。对于民众，这是干预，但更重要的是，这是唯一生存的希望。

所以，路径依赖形成了。

河南完全不像宗族势力强大的一般中国农村一样，和谐，而又腐败，土皇帝；河南强烈依赖政府的救济，又饱受其错误带来的巨大风险。政府的错误应对，几乎永远会对河南带来严重的后果。这为 1949 后的那个新政权提供了现成的社会基础。

* 1949~1978
传统社会的力量很薄弱，所以新政权在高强度的资源汲取、粮食统购统销、人民公社化运动的时候，阻力会更小，所以这个地方就顺理成章得更用力了

后来，在黄泛区现成的治理模式，无意中为后来的国家建设建成了一个很好的试验场，人民接受度很高。

1949 年之后，国家机器以前所未有的深度下沉到了基层。

第一，就是吸取资源，河南是一个农业大省，牺牲了自身积累为代价，为新生的国家工业化提供了无价的原始资本。国家的失败也在此地被不成比例地放大了。

第一件事就是统购统销。1953 开始实行统购统销, 国家强制力, 非市场化地低价收购粮食, 这些农产品通过工农业产品剪刀差, 把农业给工业用。

这个非常好想，低价收农业的粮食，发到城市去给工人配齐口粮，让工人进行工业化。农民的剩余价值，被源源不断的分配到需要工业化的城市去。这个利益链条一旦形成了，河南就被牢牢地锁在了粮仓的定位之上。这个时间段是非常残酷的，我们可以以大跃进时期的信阳事件为例子，实际 217 亿斤左右，省委上报到了 1000 亿斤。信阳地区当年的实际产量在 21 亿斤左右，上报到了 72 亿斤，税收也翻了四倍，省委给信阳下达了 9 亿斤的征收任务，也就是说一半的粮食要征收出去，而且地方官员还会层层加码，最后是有 16 亿斤的粮食被收了上去。

这意味着，当地农民的全部余粮、口粮、种子粮、饲料粮，全部都交了。而且，作为调节机制的反销粮严重缺位了，饥荒最严重的时候，国家的粮仓里是有粮食的，但是信息高压，开仓赈济的决策没有来到，最终，百万级的非正常死亡。这是河南的缩影。

1952~1957 年间，河南的人均产量大概是在 250 公斤左右，到了 1960 年已经降低到了 145 公斤，全省最低。

这种高强度的资源汲取，一定要有一个基层组织发挥作用，人民公社。为了完成不切实际的征购指标，地方政府开展了普遍的反瞒产私分运动，信阳这个地方，动用了民兵挨家挨户地搜查农民的私藏粮食。过程……唉

反右倾的政治高压，提出异议的干部都会被打倒，谁说实话谁挨批，向上传递的政治渠道被堵死了。灾难在无人纠错的情况下，不断恶化。遂平县是全国第一个人民公社发生地，所以其卫星产量被虚报了，直接触发了后面的高征购和严重的饥荒。

国家政策通过政治运动不断加码，最后在基层以最残酷的形式执行了。而且，错误的承担成本是不成比例的，你可能说错一句话，在河南就可能有人饿死。同样的政策失误，在城市地区就没造成饥荒，在农村地区就造成了如此大的后果。

国家太太太在乎工人, 太太太不在乎农民了。听一个不可名状的人说的话: "如果要等农民吃饱了, 国家才征贡, 那么城里人就没的吃了, 工业化就搞不成了。"

城里人是有固定的口粮配给的，但是农村里就成为了人间地狱。不是天灾，是人祸，是通过强制手段进行不合理的资源再分配，是出现严重后果后整套调节机制失灵的直接恶果，在河南，整套制度的失误被无限放大，造成了整整一代人的血泪为后果。

** 改革开放 1978 ~ 2010
河南的定位还是没有变，只是从前 30 年汲取河南的粮食物资，到后 30 年去更大规模地，汲取河南的人、身体。

第一件事是务工潮，1980 年代开始的务工潮。

沿海地区作为世界工厂，需要巨大的廉价劳动力，河南拥有庞大农业人口，最理想的人力资源库，数以万计的青壮年前往了珠三角长三角京津地区，用他们的血汗铸成了中国工业的奇迹。到 2010 年，全国农民工总数已达到 2.42 亿，河南是这只大军的主要来源。

这些新生代的农民工和他们的父辈不同，他们年龄更低，文化程度更高，但对农业更加疏离，他们深入城市的工地工厂，劳动保障最差安全保障最差收入最低的工作，他们的身体成为了全球资本利益分配体系的最底端，他们是中国制造业血汗红利最核心来源。

这种发展模式的巨大社会成本，绝对不是被珠三角承担的，真正的后果被外部花了，留在了河南的农村，而且它不能量化，对于官僚系统来说，没有量化就是没有价值，没有上报的价值。数百万留守儿童的教育困境和心理创伤，数百万空巢老人的养老也医疗问题，整个农业社区的空心化，整个社会结构的瓦解。

「访谈的话，去当地的医院，你能看到很多东西。」

留守是有代价的。劳动力的大量流出在社会造成了一个巨大的社会真空。河南的留守量级最高大概到了 250 万这个量级，占全国总数的 10%，面临的问题不计其数。个体家庭的悲剧，是巨大的人口悲剧的一部分。

即使不从情感上谈，这也是对未来人力成本的透支啊。你希望他们去劳动去交税，但是他们什么也干不了。他们只是承担着过去 30 年的后果。

河南牺牲了整整一代人的完整性和农村社会的可持续性，为城市化提供了动力。

** 血浆经济
如果说劳动力是身体被正常使用，毕竟还能赚点钱，还行。那么 90 年代的血浆经济，就非常的极端和野蛮了。

80 年代末 90 年代初, 为了解决血荒和用血不足, 并且发展本土生物制品产业, 国家鼓励了单采血浆技术, 同时限制了血液制品的进口, 国内市场就出现了巨大的市场缺口。河南省地方政府, 特别是卫生系统, 把发展血浆经济视为农民脱贫和系统上升的捷径。因为穷得没什么可掏出来了, 河南人他妈只能靠献血去奔小康。 「要想崩小康，赶紧卖血浆。」

单采血浆技术，还算是安全的，但是在操作中，为了追求效率和利润，血站多人利用一套设备，混合设备，在回输血细胞的时候，造成了一个巨大的安全隐患。因为单采血浆需要回输血细胞嘛，只要一个人携带了 HIV, 艾滋病就会迅速地传播至该批次的所有输血者。

我们可以看到一个剥削链条, 顶端是国内的生物制品, 中端是官方的血站, 低端是百万计的底层输血者, 为了 50 块去换取自己的身体健康。地方政府是整个利益链条的受益者, 他们通过审批和建立血站, 直接参与了利益分配。

灾难的后果是毁灭性的，艾滋病在特性卖血人群中大规模爆发，大量的艾滋村出现，比如蔡县的文楼村。大量的青壮年死亡，遗留了艾滋病孤儿，艾滋孤儿，家庭崩溃，社会歧视全部爆发了。

悲剧发生之后，地方政府采取了信息封锁的策略，打压了揭露者。呃呃。核心逻辑也不是什么腐败压抑，就是单纯地担心投资环境。为了营商环境，这种东西得压下去，不然这些商人再跑这个地方就更烂了。卖血这个昏招也是下下策，选了卖血，诶卧槽这血有问题，那如果问题再爆出来，那城市的经济就更没办法了。地方政府没的选。

所以，最廉价的生命原料，在地方发展的狂热冲动和监管的系统性失灵之间，被无情地牺牲的。

但是, 河南粮仓的定位是没有丝毫减弱的, 它依然要用 1/16 的耕地去产出全国 1/10 的粮食。这意味着留在土地上的老人和妇女需要为了保证国家的食品安全而不断劳作。农民全年无休, 但是这些孱弱的身体成了中国食品安全最后的防线。

但是他们甚至不会玩互联网, 他们的苦难无人诉说, 他们在整个互联网话语体系下是失语的, 他们是整个系统的压舱石。

走出家乡的农民工，病倒在血站的卖血者，老在土地上的农民。河南人的身体在改革开放的叙事中，被以各种各样的方式使用了。他们创造的价值被转移了，但发展的成本被留在了本地。

* 文化
