#+title: Chinese Recipes
#+author: SOV710
#+date: <2026-01-17 Sat>

* 原料的处理方法

** 猪肉

*** 头尾部分

*猪头*: 从刀口至脑顶骨斩下

*猪尾*: 从尾根处斩断

猪肉和猪尾一般用于酱、烧、煮、腌

*** 前腿部分

*前腿上脑*: 肉质较嫩, 瘦中夹肥, 做咕咾肉、桂花肉最适合

*夹心肉*: 位于前上脑下边, 肉质较老, 筋膜多, 适用于制馅、制丸及煮汤等。

在夹心肉上, 尚有小排骨 (肋骨), 可做红烧、糖醋小排骨等

*前蹄髈 (前肋子)*: 蹄髈皮厚、筋多、胶质重, 适宜于红烧、白煮、过油、扎蹄等

*颈肉 (槽头肉)*: 肉老质差, 瘦肥不分, 大都用于馅心、红烧, 也可做腐乳肉、回锅肉等

*前脚爪*: 只有皮、筋、骨, 没有肉, 抽去蹄壳后, 可做红烧、煮汤等

*** 腹背部位

*脊背*: 包括大排骨、里脊肉等。斩大排骨时注意里脊肉的完整, 并把里脊肉拿下

大排骨筋小肉嫩, 可做炸、煎、烤用。里脊肉是全猪身最嫩的肉, 可做软炸里脊、炒里脊片、汆里脊之用

*五花肋条肉 (奶面)*: 一般带排骨的称为方肉, 不带排骨的称为奶面

奶面又分硬肋、软肋。硬肋的肉质坚实

五花肋条肉一般做红烧白炖、过油、粉蒸等。油、油网等, 也可炼油或做馅料用

*奶膘 (五花肉)*: 几乎没有瘦肉, 尽是泡泡肥肉, 可作腊膘、大酥肉等

*** 后腿部位

*臀尖肉*: 位于坐臀上面的瘦肉, 很嫩, 可代替里脊肉

*坐臀*: 后腿上边的一块瘦肉, 纤维较长, 一般作白切肉、回锅肉等用

*弹子肉 (后腿肉)*: 位于分水骨下边、后腿前部的瘦肉, 肉质较嫩, 可用于炒、炸、爆, 能代替里脊肉

*后蹄膀 (后肘)*: 从介骨处卸下, 可做红烧、清炖、过油用

*后脚爪*: 在介骨处卸下, 抽出蹄筋, 后蹄筋的张发性足, 比前爪好

** 牛肉

*** 头尾部分

*牛头*: 皮多、骨多、肉少, 有瘦无肥, 适用于烧、卤制、白切

*牛尾*: 肉质肥浓, 最适用煨汤等

*** 前腿部分

*上脑*: 位于脊背前部, 靠近后脑, 肉质肥嫩, 可做烤、炒等菜肴

*前腿*: 位于上脑下部, 包括前胸和前腱子的上部, 肉质较嫩, 适用于红烧、卤、酱、熏、制馅等

*颈肉*: 质量较差, 可做红烧、煨汤、制馅等

*前腱子*: 肉质较老, 可做红烧、卤、酱等用

*** 腹背部位

*牛排*: 包括里脊肉, 位于牛脊背部, 紧接上脑, 肉质厚润、肥嫩, 一般用于烤、炒、爆

里脊肉, 肉质细嫩, 可做爆、炒等用

*肋肋*: 位于牛胸部的肋骨处, 肉中筋膜密布, 肥瘦均匀, 多用于煨汤、红烧等

*牛白奶 (胸脯)*: 位于腹部, 呈带状, 肉层较薄, 并附有白筋, 一般用于红烧; 嫩的部分, 可以爆、炒等

*** 后腿部位

*米龙*: 位于牛尾根部, 前接牛排, 肉质很嫩, 表面有油膘, 适于炸、熘、爆、炒等

*里仔盖*: 位于米龙下部, 肉质瘦嫩, 相同于米龙

*仔盖*: 位于里仔盖下面, 可做炸、熘、炒等

*和尚头*: 位于里仔盖旁边, 本身是由五条筋合拢而成, 肉质较嫩, 以炒为最好吃

*后腱子*: 肉质较老, 可做红烧、卤、酱等

** 羊肉

羊有山羊、绵羊

绵羊肉质肥嫩, 膻味轻, 皮下有脂肪层, 特别是尾巴, 全是脂肪。
山羊膻味较重, 全是瘦肉。

*** 头尾部位

*羊头*: 肉少、皮多, 用于酱、白煮

*羊尾*: 绵羊尾多油, 可做炸、爆、炒和熬油之用
山羊尾小, 皮多肉少, 肥而不腻, 可红烧、卤、酱、白煮等

*** 前腿部位

*颈肉*: 肉质较老, 夹有细筋, 可做红烧、煮、煨汤、制馅等

*前腿*: 位于颈肉后部, 包括前胸和前腱子的上部

羊胸肉嫩, 宜做烧、扒
其他肉多筋, 只宜做红烧、炖、酱、卤、煮等

*前腱子*: 肉老而脆, 肉中夹筋, 适宜做卤、酱、烧、炖、煨汤等

*** 腹背部位

*肩担肉*: 位于脊背骨外面, 形似扁担, 肉纤维长而细嫩, 可做涮、烤、炸、熘、爆、炒、煎等用

另有里脊肉, 位于脊骨后段两边, 质地最嫩

*肋条肉 (方肉)*: 无筋, 外附一层云膜, 肥瘦兼有, 越肥越嫩, 适宜于涮锅、烤、焖、扒、扣等

*胸脯*: 位于腹部, 肉质肥多瘦少, 肉中无筋膜, 可做烤、烧、扣等

*** 后腿部位

*后腿*: 羊的后腿肉比前腿肉多而嫩, 其中臀脊肉 (大三叉) 肥瘦各半

臀脊下面的一块瘦肉为摩挡肉, 形状如碗, 纤维纵横, 肉质粗而松, 肥多瘦少, 宜于做烤、炸、爆、炒

与摩挡肉相连处, 形如两条相连的黄瓜, 一条斜纤维, 一条直纤维, 名为黄瓜条, 肉质细嫩, 可代羊里脊肉用

*后腱子*: 肉质和用途与前腱子相同

** 鸡

*脊背 (鸡子肉)*: 脊背两边各有一块。此肉不老不嫩, 无筋, 用于切丁

*腿肉*: 腿肉较厚且老, 宜于切丁、切块之用

*胸脯肉和里脊肉*: 胸脯肉是从颈部三叉骨起至尾部贴脊椎骨和胸骨的肉, 肉质很嫩, 适于切片、切丝

里脊肉是取掉胸脯肉之后, 贴胸骨突起处的两条里脊肉。此肉最嫩, 宜于切片、剁茸之用

*鸡爪*: 可用于酱、卤或煮汤

*鸡头*: 可用于煮汤

*鸡颈*: 可用于煮汤、出肉

* 原料的选择方法

*** 植物性原料

*禾谷类*: 品种很多, 但有其共同标准, 那就是:
- 首先看其新鲜程度, 检验它的颜色、光泽、气味, 有无虫咬或变质
- 其次是干湿程度, 含水量不宜过大; 其三是看有无杂质或霉粒。

*豆及豆制品*:
- 对鲜豆和豆荚的选择, 以新鲜、肥嫩、无虫咬为最好
- 而干豆类则以粒大、均匀、质地坚实、富有光泽者为好
- 对豆制品, 则要求细嫩、均匀、厚薄一致、水分适当为佳

*蔬菜瓜果类*: 以色泽鲜艳、个大、无斑点, 有其特有气味者为好
- 菜类中的根菜类, 以生脆不干瘪、表面光亮滑润、水分充足者为佳品
- 叶菜类以叶身肥壮、色泽鲜艳、菜质细嫩者为上等

*** 动物性原料

*家畜类*:
- 猪、牛、羊等家畜肉的选择, 以肉质紧密、富有弹性、色泽鲜艳、气味正常者为好
  - 例如猪肉以皮薄、膘肥, 且肥膘部分色泽雪白, 瘦肉部分色泽淡红者较好。质量差的猪肉, 不仅肉质松软, 而且色泽发暗, 气味不正常。

*家禽类*:
- 对活鸡、鸭、鹅的选择, 主要看其羽毛是否丰满滑润, 行动是否活泼
- 对光鸡、鸭、鹅 (已经宰杀褪毛处理的) 的选择, 则以肉质是否肥壮、坚实、新鲜为标准。骨硬, 脚上鳞片粗糙无光, 口不整齐, 羽毛粗糙发卷; 老鸭嘴坚硬, 羽毛蓬松, 脚上鳞片粗糙。

*蛋品类*:
- 新鲜的蛋品 (包括鸡、鸭、鹅蛋) , 外壳清洁, 表面粗糙, 光泽不显著, 用手摇时无振荡, 用灯光照射, 蛋内空头很小, 完全透明, 蛋黄轮廓清晰, 无斑点, 无红影
- 松花蛋则以个大、蛋质柔嫩, 蛋白黑而透明, 蛋黄带绿色者为好
- 糟蛋则以蛋黄软嫩, 蛋白呈薄糊状, 饱满而完整, 气味芳香者为好。

*水产类*:
- 对鱼类的选择, 一般以鱼鳞紧贴鱼身, 肉质坚实, 鱼鳃鲜红, 眼珠透明而凸出者较好
- 鲜虾色泽清白, 头尾不脱落, 并且有一定的弯曲度
- 活蟹壳青腹白, 大腿肉质坚实, 如将其背朝下、腹朝上放置, 则会很快地翻转过来

*** 干货原料
干货原料, 系指脱水干制而成的原料。其中包括干菜类与山珍海味类。
一般要求干燥、体轻、整齐、不霉烂、不出芽、无虫蛀、无杂质, 并能保持新鲜时的色泽为佳

*燕窝*: 燕窝是我国福建泉州、广东崖州沿海地区一种金丝燕的巢。这种金丝燕以海里的小鱼、小虾和海藻为食物, 经过胃液消化一部分变成胶状物, 象丝一样吐在海边崖石上营巢, 即为燕窝。
其中​*血燕*, 粉红色, 不杂有燕毛, 极贵; *白燕* (又称官燕), 灰白色, 外有稀疏细毛, 次之; *毛燕*, 毛多而糊密, 更次之。

*鱼翅*: 鱼翅是用板鳃类鱼鳍制成。各种鲨鱼和几种少数鳐科鱼类的鳍都可以作为原料。
背鳍叫脊翅, 臀鳍叫勾翅, 尾鳍叫尾翅, 脑鳍叫翼翅 (又名牙筋翅) 。
旅顺、大连一带的​*玉吉翅*, 肉细嫩、翅针柔嫩为上等品; 沿海一带的​*合包翅*, 体形较大, 质地次于“玉吉翅”; 日本出产的​*白翅*​里外灰白, 外皮细腻而发光; 我国福建、台湾出产的​*大青翅*​、​*尖翅*​等则翅多、肉少。

*鱼肚*: 为鱼腹中的浮沉气管——鱼鳔干制而成。
其中以​*雄黄肚*​最好, 厚半寸余, 最大的一四斤多重; 其次是黄色透明的​*广肚*, 体小质厚; 其他品种质量较差。

*鱼骨*: 又称明骨, 是鲨鱼的骨头。普通的脑骨也叫鱼骨。产于广东。吃时发脆。

*鱼皮*: 即鲨鱼的皮。产地和鱼翅相同。有青鱼皮、沙婆皮、老虎皮、海牛皮、石岛皮、玉吉皮。

*干贝*: 俗称江干, 是一种海蛤, 叫扇贝 (又名海扇、贝干蛤) 的闭壳肌干制成。另外一种与干贝极相似的江瑶柱, 是江瑶蚌闭壳肌干制成, 但不是干贝; 我国烟台、大连产量最多。

*鹿筋*: 鹿筋系梅花鹿腿上的筋, 带蹄者为蹄筋 (与猪、牛、羊的蹄筋不一样) , 不带蹄的为鹿筋, 是吉林省的特产, 营养很丰富。

*猴头*: 猴头又名猴头菜, 是生长在树权间的一种菌类, 皮外有黄色的茸, 体积与形象均与猴子的头相似。
吉林产的最佳, 洛阳产的次之。

*银耳*: 银耳又称白木耳, 属于菌类, 产于四川、贵州等地。
其中以黄白色、干燥、朵片大、肉厚而有香味、无斑点者为佳。
银耳与燕窝能互相补益, 故名贵滋补中, 上燕窝之后, 随上银耳汤。

*海参*: 海参是一种棘皮动物, 体长五、六寸, 形如胡瓜, 圆而软滑, 黑色, 我国沿海皆产。
有梅花参 (刺参) 、光参 (海茄子) 两大类。刺参体黑多块状, 肉肥多刺, 略呈花瓣形, 产于辽东半岛沿海者称辽参 (俗名红旗参) ; 产于广东沿海者为广参; 产于浙江者为瓜皮参。

*蚝子*: 蚝子是水产贝类动物, 即花蛤蚝。产于我国沿海一带。

*果子狸*: 果子狸是山间动物, 以食果木为生。特点是肉鲜, 鲜味长。

*菜心*: 菜心是指蔬菜的心, 有四季之分, 一般常用的有飘菜、菠菜、菜苔、小白菜等, 起配色作用。

*南槽*: 南槽即绍酒糟, 产于浙江绍兴, 冬季最常用。具有糟香味。

*京冬菜*: 京冬菜产于开封, 起配色作用。

*生菜*: 生菜有叶生菜、花叶生菜之分, 产于河南开封。

*鲜蘑菇*: 鲜蘑菇属于真菌类, 腐木所生, 人工培植、野生的均可食用, 有鲜嫩、提味之特长。

*荸荠*: 荸荠属于水生植物。河南杞县荸荠最好。特点是脆嫩利口, 有甜味。

*口蘑子*: 口蘑子又称羊奶口蘑, 产于长城以北内蒙一带。

*玉兰片*: 有冬片、春片、桃片、尖片、兰薹、笋衣六种, 其中以尖片最嫩, 干燥、肉厚、根小、干净者为好。

* 原料的加工和整理

原料的初步加工和整理, 直接关系到菜肴的色、香、味、形, 同时影响到食品的营养价值。

因此, 在加工中一要注意清洁卫生；二要注意保持营养成分, 如蔬菜要先洗后切, 切了即用, 以防养分流失；三要做到物尽其用。

** 刀工

刀工是根据烹调和食用的需要, 将各种原料加工成一定形状的操作技术。刀工的基本要求是:

1. 整齐划一。无论是丝、丁、条、块或其他形状, 都必须粗细一致, 厚薄一致, 长短一样, 才能使菜肴达到色、香、味、形俱佳, 符合卫生要求, 老嫩一致, 调味均匀。

2. 干净利落。在进行刀工操作中, 不论是条与条之间, 丝与丝之间, 块与块之间, 都不能藕断丝连, 似断非断。

3. 根据原料的不同性质, 采用不同的刀工方法, 切成不同形状。如同样是块, 带骨的块要小些；同样是丝, 牛肉老筋多, 应横着纤维的纹路切；猪肉筋少, 应顺着或斜着肌纤维的纹路切。

4. 适应不同的烹调方法, 采用相应的刀工方法, 如焖、爆、炒等, 火力旺, 时间短, 必须切得薄一些、小一些；焖、烧、炖等, 用火力较小, 时间较长, 带有较多的汤汁, 要切得厚一些、大一些, 不然易成糊状。

5. 形状协调。一般辅料服从于主料, 主料与辅料形状大体一致, 而且主料稍比辅料大些, 达到主次分明, 协调一致, 成熟均匀。

** 刀法

刀法是用刀使原料成为各种形状的方法。常用的刀法有:

*** 切
切一般用于无骨的原料, 切的刀法包括以下几种:
1. *直刀切*, 又名跳刀, 方法是一手按稳原料, 另一手持刀, 一刀一刀笔直地切下去。
2. *推切与拉切*​。推切的刀法是切时刀由后向前推切下去, 着力点在刀的后端, 一刀推到底; 拉刀的刀法是切时由前向后拉切下来, 着力点在刀的前端, 一刀拉到底。
3. *锯切*, 又名推拉刀法, 先将刀向前推, 然后再拉回, 一推一拉, 象拉锯一样切下去。
4. *剁切*, 有两种方法。一种是右手握住刀柄, 左手握刀背前端, 提起刀柄, 使刀柄高于刀尖, 刀尖下垂按在原料上, 对准要切的部位, 用力将刀根向下压切下去, 与使用铡刀的方法相似；另一种切法是右手握住刀柄, 将刀放在原料要切的部位上, 左手按住刀背前端, 左右两手交替用刀摇切下去。
5. *滚切*, 即每切一、二刀, 即将原料滚动一次再切的刀法。

*** 片
一般用于无骨的原料, 片的刀法包括以下几种:
1. *平刀片*, 是将刀身放平, 使刀与砧板平行, 刀的前端紧贴砧板, 后端略为提高, 左手按稳原料, 右手执刀一刀到底。
2. *推刀片与拉刀片*​。推刀片是将刀身放平, 片进原料后, 由内向外推移, 多用于煮熟回软的脆性原料；拉刀片同样是放平刀身, 片进原料后由外向里移动, 多用于韧性原料。
3. *斜刀片*, 又称抹刀, 以左手指按稳原料左端, 右手执刀, 片时刀口向左, 刀身倾斜, 从原料表面靠近左手的部位向左下方运动, 一刀到底。
4. *反刀片*, 是刀背向里(身边) , 刀口向外, 刀身微呈倾斜状, 片入原料后由里向外运动。

*** 剁
剁也叫斩, 是将原料加工成茸或末状的一种刀法。两手同时提刀操作, 称为排斩。运用手腕力量, 此起彼落, 从左到右, 反复排斩, 将原料剁得均匀细致。

*** 劈
1. *直劈*, 将刀对准原料要劈的部位, 用力向下直劈, 常用于带骨或质地坚硬的原料。
2. *跟刀劈*, 将刀刃先嵌在原料的部位内, 刀与原料一齐起落, 适用于一刀不易劈断的原料, 如脚爪、蹄膀等。
3. *拍刀劈*, 将刀放在原料要劈的部位上, 右手握住刀柄, 左手用力在刀背上拍下去, 将原料劈断。此刀法适用于圆形、椭圆形或体小而滑的原料, 如鸡、鸭头等。

*** 划
划是采用几种切和片的刀法, 将原料划上各种刀纹, 但不切(或片) 断的一种综合刀法, 可以分以下几种:
1. *推刀划*, 以左手按住原料的后部, 右手执刀, 刀口向外, 紧贴住左手中指片入原料三分之二即止。
2. *拉刀划*​。左手按住原料, 右手执刀, 刀身外倾, 将刀由外向里拉进三分之二左右。
3. *直刀划*​。直刀划与推刀切的刀法相似, 只是不将原料切断而已。

** 刀口

经刀工处理后的原料的形状, 称为刀口。大致可以分为:

*** 花刀
1. *荔枝和麦穗花刀*, 是将原料先用推刀划一遍, 再用直刀与第一次成斜十字交叉划一遍, 然后改成块。如切成象眼块, 烹调后即可卷缩成荔枝形；切成长方块, 可成为麦穗形。
2. *钉子花刀*, 是横竖都用直刀, 划成一个个小方格, 再切成片。烹熟后象一排排的钉子, 因其花纹与核桃纹相似, 故又名核桃花刀。
3. *梳子花刀*, 是先用直刀划, 再把原料横过来切成片, 烹熟后象梳子形状。
4. *蓑衣花刀*, 是在原料一面, 象荔枝花刀一样过一遍, 再将原料翻过面用推刀普划一遍, 其刀纹与正面斜十字花纹互相交叉, 两面深度均为五分之四, 再切成一寸见方的块, 提起来呈蓑衣状。

*** 块
块是用切或劈加工成的原料, 可分为象眼块、长方块、斜指块、劈柴块、大小块、斧头块、滚刀块等。一般用于烧、焖的块要大些；用于爆、炒的块要小些；质地松软、脆嫩的块要大些, 质地硬的要小些。

*** 片
片是直刀切成平刀、斜刀片的方法, 将原料切成薄片, 有柳叶片、指甲片、雪花片、月牙片、刀背片等。用于汆的要薄, 用于炒、爆、焖的稍厚一些。

*** 丝与条
条与丝相似, 但条比丝细。条一般长一寸, 宽三四分, 故有一四条之称。

*** 丁、粒、末
丁比较小, 由条加工而成。可分为小方丁(骰子丁) 、菱角丁、螺头丁(如螺子头状) 。
粒比丁小, 由丝加工而成, 大小与米粒相仿。
末更小, 是由丁、粒斩碎而成。

*** 茸、泥
将原料捣烂或剁烂为茸、泥。泥比茸更细、更烂。

** 配菜

配菜就是根据菜肴的质量要求, 把各种成形的原料加以适当配合, 使其成为一只完整的菜肴原料。

*** 配菜的基本方法

配单一料: 就是指这类菜只有一种原料构成, 要突出其优点, 避免缺点。如各种蔬菜要选其鲜嫩部分; 鱼翅、熊掌营养价值高, 但本身缺乏鲜味, 必须配一些鸡肉同烧, 然后再拣去鸡肉, 单一上席。

配主辅料: 就是指一种菜肴, 除主要用料以外, 还配一定数量的辅助原料。配辅料的目的, 主要是对主料的色、香、味、形及营养成分起调剂作用。例如走油肉、香槽肉、过油油腻, 配一些蔬菜, 可使主料的色彩鲜明, 味道肥而不腻。又如洋葱猪排, 配洋葱有助于增加猪排的香味。凡有主辅料的菜肴, 主料在数量、质量上都占主位；辅料居次位, 起陪衬、烘托的作用。另外要根据菜肴的质量和烹调要求来确定谁为主料, 谁为辅料, 辅多少。

配不分主辅的多种料: 就是指菜肴由两种以上、数量相仿的原料所制成, 而且不分主次。这种配菜方法要慎重处理, 尤其对那些体积大小不一、口味浓淡悬殊的原料, 在用量方面要作适当调整, 保持平衡。例如爆双脆中用的鸡鸭肫和猪肚, 都是剖中带脆的原料, 形状大体一致, 就会成熟均匀, 味道调和。

配花色菜: 就是指在色和形方面特别讲究, 使菜肴富于艺术性, 喜人悦目。其配菜方法灵活多变, 常用的有:

叠: 就是把不同颜色、不同口味的原料, 分别加工成相似的片状, 层层叠起来, 中间抹上糊状原料使其粘在一起。如“锅塌鱼片”。

卷: 卷就是用各种韧性原料削成较大的片, 再将各种不同滋味、不同颜色的原料切成细丝或茸末, 铺在片上, 抹上糊再卷成卷。如“五丝鱼卷”“炸佛手卷”等。

排: 就是将加工好的各种不同形状、不同颜色的原料排成美丽的图案。如“什锦火锅”, 造型大方, 美观耐看。

扎: 就是把切成条或片的原料, 用黄花菜或干菜捆成一束一束的形状。如“柴把鸭子”“菊花糯锅”等。

瓤: 是在一种原料的中间, 填入其他原料(一般是茸状或末状原料) 。例如“瓤辣椒”“瓤西红柿”“瓤八宝鸡”等。

包: 就是把鸡、鱼、虾、猪肉等鲜嫩无骨的净料加工成片或茸, 用网油、蛋皮、荷叶包裹起来, 加热制成。

*** 配菜应注意的事项

1. 注意营养成分的配合。如肉类含蛋白质、脂肪较多, 蔬菜含维生素较多, 两者相配, 营养更加丰富。

2. 注意色调和谐, 色泽鲜明。既要考虑原料本身的颜色, 也应掌握加热后颜色的变化。如“百鸟朝凤”就将鸡脯肉泥加五色汁, 炸成五色丸, 放在蒸鸡周围, 颜色新鲜, 五彩相映。

3. 注意香和味的配合。香和味的配合比较复杂, 比如动物性原料, 气化后发出种种芳香气味, 如加些洋葱、大蒜、芹菜等含有芳香的原料可更加香美。如配些香味清淡的原料可以调和。但是, 味道相似的不宜配合, 例如牛肉和羊肉、青鱼和黄鱼、马铃薯和芋头、丝瓜和黄瓜等, 配在一起不到互相调剂的作用。

注意形的配合。各种配料形状要调和, 尤其配花菜时, 要构思完整, 形象清晰, 美观大方。

*** 干货发制

干货都是经过脱水干制而成。干货原料的发制, 分水发、油发、盐发三种。

**** 水发

水发是最常用的发制方法, 除了有粘性、有油质及表面有皮鳞的原料以外, 一般都用水发。水发又分为冷水发、热水发和碱水发。

1. 冷水发
冷水发是把干料放在冷水中, 浸泡相当时间, 让其吸收水分而膨大回软。这种方法适用于体小质软的干料, 如冬菇、香菇、银耳等, 直接用浸的方法就可以胀足发透。除此之外还可以和其他发制方法配合使用。如鱼翅和海参可以先浸一段时间, 再煮发, 可以避免煮时外表破裂, 也便于开肚去沙；干贝、蛏土蚌则应先浸3—4小时, 再上笼蒸发, 才可以保持原料的胶质和鲜味；鲍鱼、干贝等, 先用冷水浸5—6小时, 再用碱水发, 可减少碱液对原料外层的直接腐蚀作用。

2. 热水发
把干料放在水中, 经过煮、焖、蒸等各种不同的加热过程, 或放在温水或沸水中泡, 使它迅速吸收水分, 膨大回软叫做热水发。可以根据各种干货的不同特点, 采取相应的方法:

煮: 一般个大、质硬或外面有泥沙的原料, 都不易发透, 必须放水中烧煮, 才能使水分渗透内部, 比如海参、鱼翅、鱼皮等须用煮发, 或煮、焖结合。

焖: 焖是煮的一个连续过程。原料在水中煮沸后, 如继续烧煮下去, 容易造成皮开肉烂, 影响质量, 则把原料连水一起倒在其他容器中, 盖好盖保持温度, 焖一定时间, 达到胀发的目的。

蒸: 将一般易于碎散的原料置于笼上蒸制, 可以保持原料的形状和气味。不同的原料也采取不同的蒸法, 比如鲍鱼需连续蒸几次, 在蒸第二次时, 应加入鸡头、肉骨同蒸, 用以增加鲜味；蒸干贝时需加入黄酒、葱、姜以除去腥味；蛏土蚌蒸时上用清水蒸后漂清即可。

泡: 将干原料置于沸水或温水中泡发一定时间即可。但要注意气候冷热, 如银耳、鱼干、发菜、粉丝在冬季用沸水泡, 夏季则应用温水泡。

3. 碱水发
把干料先用清水浸发, 再放在碱溶液里泡相当时间, 促使其膨发回软叫碱水发。由于碱水的脱脂及腐蚀作用, 能溶去坚硬干货外部的油脂和胶脂以便加速水分的吸收, 但又有一定的腐蚀作用, 因此要注意几点:
- 碱水发主要限于一些性质十分僵硬、用热水发不透的干料, 如鲍鱼、螺脯等。
- 碱水的浓度要根据原料的不同性质而定。通常用的是用碱7%、石灰3%及开水90%拌和(碱和石灰溶合, 发生苛化反应, 生成氢氧化钠, 促使原料进一步吸水膨发) , 待其澄清后, 除去沉淀物即可食用。
对于性质不十分坚硬的原料, 如海参、鱼皮等, 可再加入50—100%的冷水使用。
- 用碱水发的原料, 可先用冷水浸一浸, 使大块的分开, 再放碱水中泡发, 但必须掌握好时间, 不要过长；发后一定要用凉水漂去碱味和脏物。

**** 油发

油发是将干货原料放在足量的油锅中, 经过加热, 使内部水分蒸发, 变成松脆、膨胀的熟料。一般用于含油质、粘性较重的干货, 如肉皮、鱼肚、蹄筋等。发前一定要干燥, 油量以淹没原料为佳, 投料时不宜过热(或与冷油同时下锅) , 火力不要过旺, 特别是原料已胀大时应用温火处理, 要勤翻, 使其受热均匀, 炸一会捞出稍停再炸, 反复多次, 炸透为止。捞出后, 要在温水或冷水中泡一至两天, 使其膨胀、松软, 清除油分和杂质。

**** 盐发

把干料放在盐锅中, 经过炒或焖相当时间, 使其膨胀松脆即为盐发。如干货干燥可与盐一起下锅；如干货受潮可先将盐炒热, 再将干货下锅。其应用范围和操作要点与油发基本相似。

* 烹调技术

烹就是对原料的加热处理, 调就是调味。烹调就是将切配好的净料, 通过加热和调味, 制成完整的菜肴。

烹调技术是一门艺术性、科学性非常强的科学技术。菜肴质量的高低, 除决定于原料本身质量的高低外, 全靠火候的大小, 加水用油的多少, 调味的区别, 投料的先后, 汤汁的稀稠, 上浆挂糊的薄厚, 动作的快慢来决定。所以, 要想烹制出精美的菜肴, 必须掌握一定的烹调技术。

** 火候

掌握火候即是对菜肴加热时, 掌握火力大小和时间长短的一种方法。由于各种原料老嫩、软硬性质不同, 大小、厚薄形状不等, 同时要制成或者香脆、或者鲜嫩、或者酥烂的各种口味的菜肴, 就要用不同的火力和不同的加热时间。

*** 火的种类

*旺火*, 也称​*武火*​​、​*急火*​​、​​*大火*​​。旺火的火苗熊熊地燃出炉口, 火焰高而稳定, 呈黄白色, 光度明亮, 热气逼人。适用于快速烹制, 如汆、烩、炒、爆、炸、煸等。

*中火*, 也称​*文武火*​。火苗燃出炉口, 火焰略有摇晃, 呈黄红色, 光度较亮, 热气大。适用于烧、煮等。

*小火*, 也称​*文火*​、​*温火*​。小火的火苗不燃出炉口, 火焰较小, 时有起落, 呈青绿色, 光度暗淡, 热气不太大。适用于煎、贴、焖等。

*微火*, 也称​*活火*​。其火焰最小, 供热微弱。一般用于炖、焖、煨等。

*** 原料的加热处理

在烹制过程中, 对原料的加热处理有油熟、水熟、汽熟、火熟四种。

*油熟*: 即用油做加热体。比如炸、爆、炒、煸、煎、贴、焖等, 一般用旺火, 使食物外焦内嫩, 有干香气味。油的传热能力较差, 沸点在200℃—300℃之间。根据一般习惯, 把油的温度大致分为三个类型:
1. 温油, 俗称三、四成热, 温度在70℃—100℃之间, 无青烟, 无声响, 油面较平静。
2. 热油, 俗称五、六成热, 温度在110℃—170℃之间, 略有青烟, 四周向中间翻动。
3. 大热油, 俗称七、八成热, 温度在180℃—220℃之间, 有青烟, 油面仍较平静, 用勺搅动时有响声。

究竟应用哪种油温下锅, 要根据原料的质量和火力大小来定。一般来讲, 旺火, 原料下锅前油温要低一些；温火, 原料下锅时油温要高一些。原料质老体大, 油温要高一些；原料质嫩体小的, 油温低一些。原料数量多时, 油温要高些；原料少时, 油温要低些。总之要酌情而定, 灵活掌握。

*水熟*: 即用水做加热体。比如煮、炖、焖、汆、涮及部分蒸、烩等。一般用中、小火, 使食物养分溶于汁内, 致使食物软烂, 汤汁鲜美。水的传热能力较强, 原料什么水温时下锅, 要酌情而定。蔬菜, 特别是绿叶菜, 必须在水沸后方可下锅, 以减少维生素的损失。

*汽熟*: 即用气体做加热体, 比如蒸、焐, 常用旺火。蒸能使食物保持原形, 养分损失较小, 菜肴柔软鲜嫩。但蒸不易入味, 所以加热前或加热后要进行调味。

*火熟*: 即用火直接做加热体, 比如烤、焙, 常用旺火。烤又分敞开烤、炉烤和泥烤。敞开烤, 即把食物直接放在火上受热, 能使食物外部干香酥脆, 内部鲜嫩。炉烤, 比敞开烤养分损失较多。泥烤, 即将原料用泥层包住或烧、或烤, 能保持较多养分, 口味特别鲜嫩。

** 制汤

汤的质量好坏, 对于菜肴的质量有着很大的影响。特别是象鱼翅、海参、熊掌、燕窝等贵重而本身又无滋味的原料, 必须靠鲜汤来为它们提取滋味, 因此制汤是很重要的一环。制汤一般分为鲜汤、白汤、清汤三种。

1. 鲜汤

汤混白色, 是平常应用最普遍、最简单的一种汤。是将鸡、猪肉、蹄膀、猪骨等原料洗净后, 放一只大汤锅中, 烧沸后撇去浮污和血沫, 加盖继续加热, 至鸡、鸭肉成熟(熟的程度应根据原料用途而定) 取出。猪骨继续煮熬, 直至汤色混白即成。这种汤浓度较差, 鲜味不足, 只能作一般菜肴调味使用。

2. 奶汤 (也称白汤)

一般是用鸡和鸭的骨架、猪肉、猪脚、猪骨等, 冲洗干净后, 放锅内, 加凉水用旺火烧沸后, 去掉汤面上的血沫和浮污, 然后再加入葱、姜、酒等, 加盖继续用中火煮到汤呈乳白色为止。用料一般是十斤原料只能制汤十至十五斤。这种汤鲜味和浓度均较高, 能增加菜肴口味的浓度与鲜味, 一般作为焖、炖、煮等白汤菜肴的汤汁, 以及烧、扒等比较讲究的菜肴调味之用。

3. 清汤

汤汁澄清, 口味新鲜, 用于高级菜肴烹制。通常分为一般清汤和高级清汤两种。一般清汤的制法是: 将净肥老母鸡、肥鸭、猪排等原料放入锅内, 加大量清水(以淹没原料为度) , 用旺火烧沸后, 撇去浮沫, 再移到文火上, 保持微沸, 翻小泡, 煮制二、三小时左右, 使原料的鲜味全部溶于汤汁内, 将鸡等捞出另作他用, 用细布或细筛过滤去杂质, 即为清汤。

若使色更清, 待汤稍凉, 撇去浮油, 再将鸡腿和猪肩担肉茸放于汤内, 略加一些葱、姜、酒等调味品, 移于旺火上, 一面煮, 一面搅, 将沸时, 停止搅动, 改用微火(不能使汤翻滚); 汤沸后, 用手勺撇出鸡腿茸, 制成澄清的鲜汤。这种清汤方法, 称为“打红哨”；如果用鸡脯肉剁成茸进行清汤, 称之为“打白哨”。打红、白哨的作用在于: 鸡茸能使汤内所有茸状细微之物粘结在一起, 便于撇出, 使汤澄清, 同时可增加汤味的鲜美。

** 挂糊、上浆和勾芡

1. 挂糊、上浆

挂糊、上浆是把经过刀工处理后的原料, 放在事先制好的糊内拖过, 糊较厚, 一般多用于炸、焖、煎、贴等烹调方法；在经过刀工处理后的原料内直接加入粉芡、蛋白及调料, 一起调拌为上浆, 其糊较薄, 多用于爆、炒等烹调方法。

挂糊、上浆, 主要是为了使原料在加热过程中, 不直接接触传热体, 保持原料中的水分和鲜味, 使其达到外部香脆或柔滑, 内部鲜嫩味美；保持原来形态, 使其光润饱满, 增加美观, 增加养分。

2. 糊、浆的种类

(1) 蛋清糊: 挂糊料, 主要用蛋白、粉芡调制而成。适于软炸等, 能使菜肴滑润软嫩, 色泽白中微红。上浆料, 主要是用蛋白、粉芡、盐制成。适于滑焖、滑炒等, 能使菜肴柔滑软嫩, 色泽洁白。

(2) 蛋粉糊: 挂糊料, 主要用全蛋(蛋清、蛋白全用) 、粉芡调制而成, 适用于炸、焖等, 能使菜肴外酥脆、内松嫩, 色泽金黄。上浆料, 主要用全蛋、粉芡、盐, 适用于炒, 能使菜肴滑嫩, 略带黄色。

(3) 蛋泡糊(又名高丽糊) : 主要将蛋白打成泡沫状(打时不能停顿) , 再加入粉芡拌和而成。多用于松炸及一些甜食或点心。可使菜肴外形饱满, 松而嫩, 色泽白里透黄。

(4) 水粉糊: 主要是粉芡加水调拌而成, 它与干粉多用于干炸、干煸等, 可使菜肴干酥香脆, 色泽紫红带黄。

(5) 酥糊: 主要是用发粉、面粉、水配制, 多用于松炸, 有膨发作用, 可使菜肴膨发饱满, 松酥带香, 色泽淡黄。

(6) 拍粉拖蛋糊: 在原料表面上先拍一层干粉(面粉或淀粉) , 然后再放在鸡蛋和芡粉制成的糊中拖过, 多用于锅贴、干煎等烹调方法。可使菜肴肥嫩, 色泽金黄。

(7) 拖蛋糊滚面包粉: 先将原料在用鸡蛋、面粉和调味品制好的糊中拖过, 然后再在面包粉上滚一滚, 多用于炸, 如炸牛排、炸猪排、炸板鱼等。可使菜肴香脆可口, 表面带有面包粉的微粒, 色泽深黄。

制糊时, 在糊或浆中不能有小粉粒, 必须搅拌均匀。搅拌时应先慢后快, 先轻后重。糊的浓度要根据原料特点及烹调要求酌情来定。较嫩的、冷冻的、立即烹调的原料, 糊都要稠一些；反之, 糊的浓度应稀一些。上述做法同样适用于上浆。

3. 勾芡

勾芡是菜肴接近成熟, 或者已烹好装盆后, 将调好的粉汁淋入锅内或装菜的盆内。目的是增加菜肴汤汁的粘性和浓度, 使菜肴光润鲜艳, 增加美观。

勾芡的粉汁是用干淀粉加水调制而成的, 称为粉芡。多用于烧、焖、煮、扒等烹调方法；如粉汁中再加各种调味品, 称为对汁, 亦叫“调味汁”或“预备调味”。它多用于焖、爆、炒等旺火的烹调方法。根据粉汁的浓度不同, 又分为:

(1) 时头芡, 粉汁最稠, 多用于爆、焖、炒等, 使汁通过勾芡基本上粘到原料表面, 食过后, 碗中不见汤汁。

(2) 大流水芡, 粉汁稍稠, 多用于烧、炖、蒸等, 使菜肴的汤汁成为薄糊状, 原料、调味品、汤汁三位一体, 口味浓厚柔滑。

(3) 琉璃芡, 粉汁较稀, 一般宜用于焖, 即菜肴煮熟出锅后, 再将锅中卤汁加热勾芡浇在菜上, 光洁明亮, 故称琉璃芡。

(4) 小流水芡, 粉汁最稀, 适用于扒等烹调方法。使汤的浓度稍稠, 口味略浓。

应当注意的是: 口味清爽的菜(如炒鸡蛋) , 质地脆嫩容易入味的菜, 具有粘性的菜(如烧蹄筋) , 都不需要勾芡。

** 调味

1. 调味的基本作用与步骤

调味的基本作用, 在于把味轻的食物加重滋味, 把味浓与味淡的食物的滋味加以调和, 把味不纯正的食物的滋味加以调正, 达到五味调和。调味一般分为三个阶段:

(1) 烹前调, 可以称为基本调味, 主要目的是使原料在加热前有一个基本的味, 并能解除一些原料的邪味腥味。其方法是先用盐、酱油、绍酒、糖等调味品把原料调拌或浸一下。有一些炸、焖、爆、炒的菜加热前往往结合挂糊上浆加入调味品。蒸的菜一般在蒸前也要进行调味。

(2) 烹中调, 是在加热过程中的调味, 称为决定性调味, 也称定型调味。具体方法是: 菜肴在原料下锅以后, 在适当的时候, 按照菜肴口味的要求, 加入调味品, 决定菜的口味。

(3) 烹后调, 也可称辅助调味, 通过这次调味可以增加菜肴的滋味。其方法是将调味品在原料加热后淋上拌匀。

2. 调味的种类与配制

调味分单一调味、复合调味两类。

(1) 单一调味有:
咸味类: 如食盐、酱油、黄酱。
酸味类: 如红醋、白醋、酸梅等。
甜味类: 如冰糖、砂糖、白糖、红糖、蜂蜜及各色果酱等。
苦味类: 一般是从药材中提取出来的, 如陈皮、准山药、芥末等。
辣味类: 胡椒粉、辣椒粉、生姜、咖喱、葱蒜等。
香味类: 桂皮、大茴香、小茴香、丁香、花椒、砂仁、石落子、香菜、芝麻、芝麻酱、麻油、香精等。
植物油: 花生油、豆油等。
动物油: 猪油、牛油、羊油、鸡油等。
鲜味类: 如虾、味精、鱼露等。

(2) 复合调味品, 系指两种或两种以上的滋味制成的调味品。其中有:
酸甜味类: 糖醋、番茄酱、番茄汁、山楂酱。
甜咸类: 甜面酱等。
鲜咸类: 鲜酱油、虾子酱油、鱼露等。
辣咸类: 如辣椒油、辣酱油等。
香辣类: 如咖喱粉、咖喱油、芥末糊等。
香咸类: 如椒盐等。
另外根据需要还可以复制很多复合调味。

3. 调味应掌握的几项原则

调味没有一个统一的方法, 只有通过实践逐步掌握。一般应掌握下列几项基本原则:

(1) 调味品份量恰当。一份菜往往有几种味, 但必须有主有次。如有些菜以酸为主, 其他为辅；有些菜以酸甜为主；还有些菜上口甜收口咸, 或上口咸收口甜。因此, 调味品的数量也必须有主有次、多少恰当。

(2) 看菜下味, 灵活掌握。不同的原料有不同的质, 也必须用不同等量的调味品。如对新鲜的鸡、鸭、鱼、虾、蔬菜等, 调味均不宜太重, 以免掩盖原料本身的鲜味；对带有腥味、膻味的鱼、虾、牛羊肉、内脏等, 都要酌情加酒、醋、葱、姜或糖等调味, 以除腥膻味；对本身无显著滋味的原料, 如鱼翅、海参等, 必须加入鲜汤, 以助其鲜味之不足。

** 装盘

装盘是烹调过程中最后一道工序, 直接关系到菜肴的形式、席面的气氛。所以装盘时要求饱满丰润, 主次分明, 色泽鲜明, 形式美观, 使食者精神为之一爽。

1. 热菜的装盘方法

(1) 左右交叉轮拉法, 一般适用于焖、爆、炒中形态较小不勾芡或薄芡的菜。其操作方法是: 先将锅颠翻一下, 把形大的或主料翻在上层, 然后用手勺将菜肴拉入盘中。拉时要左边拉一勺, 右边拉一勺, 交叉轮拉。

(2) 倒入法分两种: 一种是一次倒入法, 一般适用于质嫩易碎勾芡的菜, 而且是单一料或主辅料不分的菜。其方法是先大翻锅, 将菜翻个大身再倒入盘中。倒时速度要快, 锅离盘不易太高, 锅顺势移动保证原料不翻身。另一种是分主次倒入法, 一般适用于主辅料比较明显又勾芡的菜。其方法是先将主料较多的菜用手勺盛起, 再将下余的菜倒入盘中, 然后将手勺中的菜盛在上边。

(3) 覆盖法, 适用于无卤汁又勾厚芡的爆菜。其方法是: 先将锅翻几次, 使锅中菜肴堆集一起, 用手勺趁势将一部分菜肴接入勺中装在盘内, 再将锅中余菜盛入勺内, 覆盖上边。因这些菜卤粘性大, 不易用倒或拉的方法。

(4) 脱入法, 是先将锅作小幅度颠动, 趁势将手勺迅速插入原料下面, 再将锅拿近盘边, 把锅身倾斜, 用手勺连拖带拉将菜肴脱入盘中。一般适用于烧、炖、焖、蒸中的整只原料, 如红烧鱼即是。

(5) 盛入法。用手勺将菜肴盛入盘中, 先盛形小的块, 再盛大的成形的块。一般适用于不易散碎的成形的菜肴。

(6) 扣入法, 是先将成熟后的菜肴一块一块紧密地排列在扣碗中, 再用盘扣在碗上, 迅速翻个过, 将碗拿掉即成。一般适用于事先在碗中将主辅料排成图案, 或要求整齐完整的菜肴, 如黄焖鸡、扣碗肉等。

(7) 扒入法, 一般适用于菜肴在锅中排列成整齐的平面, 装后仍不改变形状的菜。其方法是: 先从锅内四周加油, 并将锅晃一下, 使油润入锅底, 再将锅斜倾, 用勺扒入盘内, 使菜肴不翻身、不变形。

2. 冷菜装盘的方法

冷菜装盘, 是菜肴烹制后在形状上进行美化整理的一道加工工序。从内容方面来分, 有单盘、拼盘、花色冷盘三种；从形式方面来分, 有不拘形式的装盘、排叠整齐的装盘、形成图案的装盘和点缀衬托的装盘四种。其装的方法大致有以下六种:

排: 将熟料改切后有序地摆在盘当中, 其原料大都用较厚的长方块或椭圆块。如火腿宜排成锯齿形, 逐层排叠；“盐水虾”则可以排成椭圆形。可根据形状酌情而定。

堆: 把熟料改切后堆放在盘中, 一般用于单盘。有的可配色堆成花纹, 有的还可堆成宝塔形。

叠: 把加工好的熟料, 一片片整齐地叠起来, 一般叠成梯形。有的切一片叠一片, 有的叠好再切。

围: 把切好的熟料, 在盘当中排列成环形, 层层围绕, 组成盘菜。有的在排好主料的四周, 围上一层辅料来衬托主料叫做围边。有的将主料围成花朵, 用辅料点缀中间, 成为花心, 叫做拼围。如将皮蛋切成瓦楞形围成花形, 中间放一些火腿末或肉松, 作为花心, 更为美观。

摆: 运用各种各样刀法, 采用不同形状和色彩的熟料, 在盘当中摆成各种动物或图案。此种方法需熟练的技术, 才能摆得生动活泼, 形象逼真。

覆: 将熟料先排列在碗中或刀面上, 再翻扣入盘中或菜面上, 它类似于热菜中的“扣”。如将卤鸡拆成块后, 先正面排在扣碗中, 加上卤汁, 再翻扣入盘里。

* 烹调方法

熟菜的烹调根据物料、火候及加热方法可归纳为汆、涮、煮、焖、烧、扒、炸、煸、爆、炒、煎、贴、熘、烩、蒸、烤、盐焗、焙烤、熏、卤、酱、拌、炝、腌、拔丝、挂霜、蜜炙九类三十一种。每一种烹调方法, 菜谱中皆有实例, 这里不再详述。

* 烹调术语

冒: 把食品或加工过的原料放在开汤里或开水里略微加热, 随即捞出叫“冒”。如冬天吃拌拆骨肉, 为了不冰牙, 就需要放到开汤里冒一下。

掸: 为了保持食品的脆嫩, 将其放在开水锅里迅速搅开, 立即捞出, 称为“掸”。

焯: 与掸基本相似, 只是原料下锅比掸的时间长些。经过焯的原料一般都能达到八九成熟。但必须防止焯过了火。此法多用于蔬菜。

汆: 就是把原料放入汤内加热片刻取出, 使原料所含的水分吐出来, 谓之“汆”。

罩: 把即将使用的原料放在笊篱内, 在开水里沥一下, 就叫罩。如用青菜叶当配头时, 就要先罩一下。

哈: 把半成品放进笼里, 上火稍微见见热气叫做“哈”。

透: 是将成品或半成品放在笼里蒸透, 不是蒸熟。透, 比哈的时间长, 比蒸的时间短。

冲: 把初步加工的原料盛在碗里或盆里, 浇入开水或热汤, 少停一会, 又随即滗出来, 谓之“冲”。如使用香椿时, 就要先用开水冲一下。

收: 在扒或烧制食品时, 为适当掌握汁的浓度, 将锅里多余的汁用火耗去叫做“收”。

熬汁: 与收汁基本相同, 用文火慢慢收汁叫做熬汁。

搅: 热锅凉油, 把原料下入锅里, 用勺搅开, 叫做搅。如搅炸酱。

滑: 把加工好的原料, 放入蛋清、粉芡、盐面拌匀, 下入水锅里煮熟捞出谓“滑”。

兜: 实际上是捞的意思。炸食物时, 将炸好的东西捞出来, 平时说兜出来。

养: 经过发制的原料, 如不马上用, 为防止发干或缩小, 用开水泡住叫养。

浆: 让原料在温水(温油) 中颠一颠叫浆。如炸肉皮、鱼肚时, 温油下锅, 油四、五成热时, 端锅停一停, 然后将锅置火上再炸, 如此三次, 其中停的过程即为浆。浆的目的是把食物炸得更透些。

顺: 是将加工好的原料, 在烹调以前按要求规格、数量切配过, 码在盛器里叫顺。

发: 将干货原料通过用水、油、碱、火等不同方法, 进行加工, 使其基本恢复原状叫做发。

听: 鉴别质量、成熟度及味道叫做听。有听菜、听面两种: 听菜是在食品成熟时, 用勺盛一点汁尝一尝；听面是用手拍面, 从发出的响声中判断软硬的多少。

提: 在发原料时, 为了加快发的时间, 对点碱就叫提。

解: 切原料不管用什么刀, 只要不切透都叫解。

刻: 在菜肴上用刀把原料拍烂叫刻。

惊: 和刻大致相同。把原料用刀轻拍, 不拍烂、拍裂叫惊。

麻: 把某些原料初步加工后, 炸或炒以前, 为了去掉不良气味, 增加香味, 先用酱油、料酒、盐水腌制一会叫麻。
