#+title: Food Chemistry (Part)
#+author: SOV710
#+date: <2026-01-17 Sat>

* 油脂 (Fat)

** 作用

*** 一、传热
油脂的热容量比水小, 在热量相等的情况下, 油脂的温度上升得要比水快 1 倍多。油脂沸点较高, 在加热过程中, 油温上升很快, 上升幅度较大, 能够很快达到高温。停止加热后, 油脂温度下降也较快, 这样便于在烹调过程中调节火力。

油脂在较短的时间内能够获得较高的温度, 这样可以在短时间内杀灭烹饪原料中的大部分微生物; 在​​*煎、炒、炸、爆、焖*​​等烹调方法中, 油脂能迅速地将热量传给食物, 使菜肴迅速成熟, 这样能降低菜肴中营养素的损失; 油脂能缩短加热时间, 对于烹饪原料的持水性能有重要的影响。烹制含水量大、质地新鲜的原料, 在烹饪过程中可以避免汁液的过分流失及营养素的流失, 从而使菜肴有柔嫩的口感和良好的风味。

*** 二、菜肴的保温
保温, 就是保持菜肴的温度。油脂不溶于水, 是热的不良导体, 能在汤汁表面形成隔热层, 防止汤类菜肴的热量散发。如由主料、辅料、调料, 再加上汤汁盛于一器皿内的菜肴, 因汤汁中油脂含量较大, 出锅后可以较长时间保持高温, 保温的效果好, 如红烧牛肉等。

又如云南的“过桥米线”, 将煮沸的鸡汤倒至汤碗中, 由于鸡汤表面油脂的保温作用, 客人食用时将鱼片、肉片、蔬菜及米线等易熟的原料放入鸡汤中烫熟后食用。淮扬菜“平桥豆腐”在烹制时加入猪油再烹制一段时间, 菜肴色泽明亮, 吃口滑嫩, 最关键的是油脂可以起到保温的作用, 即使在冬天也可以长时间食用。

*** 三、赋予菜肴的香气
油脂在加热后会产生游离的脂肪酸和具有挥发性的非脂成分, 部分物质散发在空气中, 或进入汤中, 从而使菜肴具有特殊的香味。

油脂也是芳香物质的溶剂。因为大多数芳香物质都是脂溶性的, 油脂能将加热形成的芳香物质由挥发性的游离态变为结合态, 使菜肴的香气和味道更加柔和与协调。如在烹饪菜肴时, 常将葱、蒜、姜、辣椒等调味料在热油锅中煸炒, 调味料中的芳香物质才能溶于油脂而产生特殊的芳香味。

*** 四、提高菜肴的色泽
恰当地利用油脂的色泽, 能达到色味俱佳的效果。例如, 猪油色泽亮白, 能够保持原料本色, 适宜烹制鲜嫩的动物、植物性原料, 使菜肴色泽明亮、洁白光亮、口感滑嫩; 芝麻油色泽深黄, 适宜炸制一些着色的菜肴, 可获得外层香脆、色泽金黄的效果; 奶油色泽洁白, 气味芳香, 适宜西菜和做糕点, 不仅颜色美观, 而且还独具风味。

如炒芙蓉鸡片, 白色的鸡片、黑色的木耳、红色的火腿、绿色的豌豆, 色调淡而艳; 滑润里脊, 汁白、肉嫩。如果用植物油, 就会影响菜肴的色泽和口味。

某些蔬菜在过油后, 油脂的油性使之呈现出鲜亮的绿色。这是由于油脂能在蔬菜表面形成一层薄的油膜, 阻止或减弱了蔬菜中呈色物质的氧化或流失, 同时也起到护色的作用。

又如爆炒类的菜肴, 勾芡后适时淋入适量的油脂, 大部分油脂会吸附在芡汁和菜肴的表面, 形成一层薄薄的油脂层, 犹如“镜面”一样可以把照射在菜肴表面的光线反射出去, 使菜肴的光泽度增加、亮度增强, 可以使菜肴光亮剔透, 提高观感, 增强进餐者的食欲。例如爆炒腰花、炒猪肝等菜肴, 都是通过油脂来达到提高菜肴的光泽度。

*** 五、润滑作用
烹饪中常用的油脂有一定的润滑性。油脂的润滑性在菜肴的加工过程中有着广泛的应用。

油脂的润滑作用主要有两点好处: 一是减少菜肴和锅壁的摩擦, 避免粘锅现象, 使晃锅和翻锅更容易, 从而有效保持菜肴形状的完美; 二是提高菜肴的润滑度, 改善菜肴质感, 更利于人们食用

烹调前, 炒锅先用油润滑后, 将油倒出, 然后将锅上火烧烫, 再加底油进行烹调, 防止原料粘锅, 避免糊底, 保证了菜肴的质量。进行热菜烹调时, 在菜肴成熟后即将出锅时, 根据成菜的具体情况淋入一定数量的油脂, 这样可使菜肴质地润滑度明显提高。

另外, 将调味料、上浆后的主料(丁、丝、片、条、块) , 在下锅前加些油, 有利于原料散开, 便于成形。烹制清炒虾仁时, 在用水淀粉和蛋清上浆时, 还可加入少量的植物油, 这样由于油脂在淀粉表面形成薄膜, 起到分散淀粉的作用, 成品虾仁不易粘连, 能够保持虾仁的形状, 外观也非常漂亮。

在面点的成形中适当用些油脂, 能降低面团的黏着性, 从而便于操作, 比如在制作馄饨、麻花时, 在手上和案板上涂点油脂, 可以使面团不粘连, 面条之间也不粘连, 从而更利于成形。在制作面包等烘烤食品时, 加入少量的油脂可以在面筋表面形成薄膜, 阻止面筋过分粘连, 使成品的质构和口感更为理想。

*** 六、起酥作用
油脂的起酥作用常常用于面点的制作中, 特别是在制作酥性面点时, 油脂是必须添加的主要原料之一。

酥性面团之所以能起酥, 是因为在面团调制时, 是用油和面一起调制的。面粉颗粒被油脂包围, 面粉中的蛋白质和淀粉不能吸收水分。蛋白质在没有水的条件下不能形成坚实的面筋网络, 而淀粉颗粒不能膨胀、糊化, 降低了面团的黏性与弹性。

当面团在反复揉制成团时, 扩大了油脂与面团的接触面, 使油脂在面团中能够伸展形成薄膜状, 覆盖于面粉颗粒的表面, 在反复揉制过程中包裹进了大量的空气, 从而使面点在加热过程中膨胀而酥松。

由于油脂具有润滑性, 使得面团变得十分滑软, 这样的面团经烘烤后能使成品的质地、体积和口感都达到较为理想的程度。

不同种类的油脂的起酥效果是不同的。猪油的可塑性、起酥性较好, 常用于酥性面点的制作。而植物油如花生油、菜子油、大豆油等虽然具有一定的起酥性, 但是起酥性不如猪油, 故在制作酥性面点时不常用。

*** 七、乳化作用
油脂与水是两种不相溶的液体, 但如果在油水混合物中加入少许乳化剂, 如一酯基甘油(也称为单甘酯) 、蛋黄中的卵磷脂或是蛋白质(如豆乳或牛乳) 等, 在强烈的搅拌下, 油脂以小液滴的形式分散在水中, 形成一种不透明的乳状液, 该过程叫乳化作用, 即油脂能够在乳化剂的作用下, 与水形成乳状液。

如“奶汤鲫鱼”, 就是利用鲫鱼中的鱼油, 烹调用油与水形成乳状液。油脂的乳化有利于人体的消化吸收。

乳状液是一种或几种液体以液滴形式分散在另一种不相混溶的液体之中所构成的分散体系, 通常把乳状液中以液滴形式存在的成分称作分散相或内相, 另一相则称作分散介质或外相。显然, 内相是不连续相, 外相是连续相。

根据内外相的性质, 乳状液主要有两种类型: 一类是油分散在水中, 这类乳状液是最常见的, 如牛奶、稀奶油、蛋黄酱、色拉调味料、冰淇淋配料等, 简称为水包油型乳状液, 用 O/W 表示; 另一种是水分散在油中, 如奶油、人造奶油、原油、香脂等, 简称为油包水型乳状液, 用 W/O 表示。

除上述两类基本乳状液外, 还有一种复合乳状液。因为油、水相不一定是单一的组分, 每一相都可能包含多种组分。如肉类乳状液, 以加工成丸子的肉糜为例, 其中肉中的水和水溶性的调味料构成连续相, 而肉中的脂肪分散在其中, 肉中的蛋白质相当于乳化剂。为了使分散体系稳定, 还可以加入一些稳定剂, 如淀粉、鸡蛋等。

** 烹调加热机理

烹调用的油脂常常是在加热情况下使用的, 如在过油、爆炒、煎炸时, 往往需要油脂在高温下进行操作。油脂的使用温度, 在多数情况下要大于150℃, 如炒菜时油温一般为180～200℃, 煎炸时油温要达到250℃。由于烹饪加热中油温较高, 油脂就很容易发生各种氧化、分解、聚合反应, 从而导致油脂增稠、颜色加深、分解、泡沫增多、发烟点下降, 产生异味等现象。餐饮业, 由于油脂循环使用次数较多, 累积加热时间较长, 更容易发生这些变化, 因此会对烹调中的食物产生一定的影响, 甚至会直接影响身体健康。

*** 一、油脂的热分解

油脂的热分解是指油脂在加热的条件下发生分解, 其产物为游离脂肪酸、不饱和烃以及一些具有挥发性的小分子物质。油脂的热分解的程度与加热的温度有关。油脂在加热还没达到其沸点之前就会发生分解作用, 在加热到150℃以下, 热分解程度很轻, 分解产物也较少。随着温度的升高, 当加热至250～300℃时, 分解作用加剧, 分解产物的种类增多。当油脂达到一定的温度, 尤其是当油脂加热至发烟点以后其质量开始劣化即开始分解, 并产生多种有毒物质。不同油脂的分解温度是不一样的。牛油、猪油和多种植物油的分解温度均在180～250℃, 人造黄油的分解温度在140～180℃。

油脂的热分解不仅使油脂的营养价值下降, 而且还会产生一些对人体健康有害的物质。如食用油脂在高温加热的情况下, 不仅使脂肪本身的化学结构发生了改变, 影响人体对它的消化、吸收, 而且油脂中的脂溶性维生素及必需脂肪酸会被氧化破坏, 使油脂的营养价值降低。又如, 油脂的热分解能产生具有挥发性和强烈辛辣气味的丙烯醛, 它对人的鼻腔、眼黏膜有强烈的刺激性。

因此, 我们应该熟悉油脂的热分解温度, 在使用油脂时尽可能避免维持过高的油温。用于油炸食品的油脂, 油温应控制在200℃以下, 以控制在150℃左右最佳, 以减少有毒物质的生成。对于专门用作油炸食物的油脂, 必须经常更换新油。对已经变色、变味、变稠、变黏的油脂, 则不能再使用。

*** 二、油脂的热氧化

油脂的热氧化是指油脂在加热条件下与空气接触时所发生的氧化反应。油脂热氧化与热分解的产物类似, 主要的氧化产物有游离脂肪酸、醛、酮、烃等。所不同的是热氧化是在有氧的条件下, 而且生成物所用的温度和时间都低于热分解。如饱和甘油酯在空气中加热到150℃就会发生热氧化。

与热分解反应类似, 饱和脂肪酸及其酯的热氧化稳定性要比相应的不饱和脂肪酸及其酯稳定。不饱和脂肪酸在常温下会发生自动氧化, 而在高温条件下热氧化与热分解会进行得很迅速, 也很彻底。

需要注意的是, 油脂的热分解与油脂的热氧化是同时进行的。反应的结果是产生大量的小分子物质, 这在有氧条件下更显著。这些物质的出现, 使油脂的发烟点大大降低, 油脂的烹调质量明显下降。

*** 三、油脂的热聚合

当加热到300℃以上或长时间加热时, 油脂不仅会发生热分解, 其分解产物还会继续发生热聚合反应, 生成多种形式的聚合物。如二、三聚环状单聚体, 能被人体吸收且毒性较强; 一聚体是由两个不饱和脂肪酸聚合而成, 也具有毒性; 而二聚体和多聚体因为相对分子质量较大, 且不容易被人体吸收, 所以毒性较小。此外, 油烟中也含有一定量的3,4-苯并芘, 是一种强烈的致癌物质, 因此长期食用油炸食品对人体的健康有害。

油脂经长时间加热后, 由于聚合物的增加, 油脂颜色加深, 黏度增加, 甚至成为黏稠状, 还会产生较多的泡沫, 这些都是由于油脂在加热中发生聚合反应的结果。

*** 四、油脂的老化

反复经过高温加热的油脂, 色泽变深, 黏度变稠, 泡沫增加, 发烟点下降, 产生异味, 这种现象称为油脂的老化, 也可叫做油脂的劣化。油脂老化不仅使油脂的质量下降、营养价值降低, 而且使烹饪的菜点风味品质下降, 更重要的是会产生很多有害物质。

影响油脂老化的因素主要有以下几个方面。

**** (一) 油脂的种类

油脂的老化与油脂饱和程度有很大的关系, 含不饱和脂肪酸较多的油脂的老化速度要远大于含饱和脂肪酸较多的油脂, 即油脂的不饱和程度越高, 油脂越容易老化。

大豆油、菜子油等, 其所含的脂肪酸不饱和程度高, 也较易老化。这类油只适合于一次性使用, 如烹调菜肴, 而不适于反复煎炸使用。棕榈油、花生油及葡萄籽油等, 其稳定性最好。这类油脂可在长时间、高温、水分存在及接触空气等苛刻的加工条件下而不容易发生变质。同时, 它们的发烟点也较高, 可用来烹饪需要在250℃高温下煎炸的食物。如棕榈油非常适用于油炸鱼排、鸡肉、马铃薯片等这样含水量高的食物。

**** (二) 油温

烹调过程中, 油温越高, 油脂的氧化分解越剧烈, 老化的速度越快。尤其是在油温高于200℃时, 油脂的老化速度更快。所以, 不要用油温过高的油脂来烹饪菜肴, 一般最好不要超过150～180℃。在烹饪中对于油温的判断很重要, 有经验的厨师一般可通过观察油表面的状态来判断油的温度。油温与油脂表面状态的关系如表5-5所示。

#+begin_quote
表5-5  油温与油脂表面状态的关系

油温/℃     状态
50～90      产生少量气泡, 油面平静
90～120     气泡消失, 油面平静
120～170    油温急剧上升, 油面平静
170～210    少量青烟, 油表面有少许小波纹
210～250    有大量青烟产生
#+end_quote

**** (三) 与空气的接触面积

油脂暴露在空气中, 与氧气接触的机会增多, 会使其老化速度大大增加, 所以油脂在此存过程中要尽量避免与氧气接触。油脂与空气的接触面积越大, 油脂的老化速度越快。在油炸食品烹调过程中要尽量减少油脂与空气的接触面积, 可选择口小的深形炸锅, 并加盖隔绝空气。在我国的一些传统食品加工中, 如炸油条, 常使用口大的敞口子锅, 这样会使油脂很容易被氧化。近年来, 已经使用了一些新型的油炸设备, 这些设备具有能通入惰性气体排除空气的装置, 有的还具有隔绝空气的装置, 能够避免油脂与氧气接触, 防止油脂老化, 延长油脂使用寿命, 提高产品的质量。

**** (四) 金属催化剂

油脂的老化也会受到铁、铜等金属离子的影响。为了减少金属离子的催化作用, 降低油脂老化速度, 应可能选择精炼油脂进行烹调加工。同时, 为了避免含有上述金属离子, 油炸类食品不适宜用铁锅、铜锅来煎炸, 而应选使用含镍不锈钢的容器进行油炸。

**** (五) 油炸物的水分含量

如果油炸食物的含水量较高, 尤其是食物表面的含水量, 会使油脂发生水解反应, 同时微生物也能在其中生长, 导致油脂发生氧化。因此烹调过程中要尽量减少油炸食物的水分含量, 如炸茄子之前可以先将茄子中多余的水分盐渍除去; 或者在食物表面裹上一层隔绝物质, 如淀粉等, 这样做也有助于避免食物中水分过分流失, 使食物鲜嫩多汁。

**** (六) 加工方式

在总加热时间相同的情况下, 油脂在连续加热情况下产生的老化要远高于间歇式加热产生的老化。因此, 不宜长期、反复地使用同一油脂, 要经常按期更换新油。对于使用过的油, 应及时捞出油脂中的食物残渣, 因为这些杂质会吸附微生物、水分, 为细菌生长创造条件, 这样往往会加快油脂的老化。烹饪中油脂的温度不能过高, 油温宜控制在200℃以下, 不要在锅内无原料的前提下空烧油锅。
